In [1]:
import pandas as pd
import json
import plotly.express as px

In [2]:
with open('./user_course_info_cleaned.json', 'r') as file:
    user_course_info = json.load(file)

df_user_course_info = pd.DataFrame(user_course_info)

In [3]:
with open('./teacher_stats_cleaned.json', 'r') as file:
    teacher_stats = json.load(file)

df_teacher_stats = pd.DataFrame(teacher_stats)

In [4]:
with open('./pro_course_cleaned.json', 'r') as file:
    pro_course = json.load(file)

df_pro_course = pd.DataFrame(pro_course)

In [5]:
with open('./price_list_cleaned.json', 'r') as file:
    price_list = json.load(file)

df_price_list = pd.DataFrame(price_list)

In [6]:
with open('./also_speaks_cleaned.json', 'r') as file:
    also_speaks = json.load(file)

df_also_speaks = pd.DataFrame(also_speaks)

In [7]:
with open('./also_speaks_reference.json', 'r') as file:
    also_speaks_reference = json.load(file)

df_also_speaks_reference = pd.DataFrame(also_speaks_reference)

Number of Records in Each Table

In [8]:
dataframe_list = [df_user_course_info, df_teacher_stats, df_pro_course, df_price_list, df_also_speaks, df_also_speaks_reference]
def get_all_df(dataframe_list):
    for df in dataframe_list:
        df.info()
        print()

In [9]:
dataframe_items = ['User Course Info', 'Teacher Stats', 'Pro Course', 'Price List', 'Also Speaks', 'Also Speaks Reference']
retrieved_languages = ['english', 'chinese', 'french', 'spanish', 'japanese', 'italian', 'german', 'korean']

In [10]:
len(dataframe_list[0])

10470

In [11]:
records = []
records_dict = {}
for item in dataframe_list:
    records.append(item.shape)
print(records)

for i in range(len(dataframe_list)):
    records_dict[dataframe_items[i]] = records[i]
records_dict

df_records_dict = pd.DataFrame(records_dict)
df_records_dict = df_records_dict.rename(index={0: 'Rows', 1: 'Columns'})
df_records_dict

[(10470, 17), (10470, 4), (39035, 8), (215827, 6), (29185, 2), (210, 1)]

,User Course Info,Teacher Stats,Pro Course,Price List,Also Speaks,Also Speaks Reference
Rows,10470,10470,39035,215827,29185,210
Columns,17,4,8,6,2,1

How many teachers of each language are there?\
During the data collection, the following languages were collected:\
English, Chinese, French, Spanish, Japanese, Italian, German, Korean\
However, since the API call is by teacher, there may be other languages taught in the dataset

In [12]:
df_teacher_language = df_pro_course.groupby(['teacher_id', 'language']).count().reset_index()
df_teacher_language_count = df_teacher_language.groupby('language')[['teacher_id']].count()
print(f'There are a total of {len(df_teacher_language_count)} languages taught')
pro_course_total = df_teacher_language_count.sum().iloc[0]
print(f'There are a total of {pro_course_total} pro courses taught')

There are a total of 147 languages taught
There are a total of 13701 pro courses taught

In [13]:
df_top_20 = df_teacher_language_count.sort_values('teacher_id', ascending=False).head(20).reset_index()
df_top_20

                  language  teacher_id
0                  english        4180
1                  spanish        2241
2                   french        1170
3                 japanese        1115
4                  chinese         998
5                  italian         818
6                   german         683
7                   korean         538
8                  russian         214
9               portuguese         173
10                  arabic         111
11       filipino(tagalog)          91
12          persian(farsi)          69
13                   hindi          67
14      chinese(cantonese)          65
15                 turkish          65
16               ukrainian          55
17  arabic(modernstandard)          54
18                 catalan          47
19                 serbian          47

Although only teachers of 8 languages were retrieved from the platform, there are another 139 languages taught among these teachers.

In [14]:
fig = px.bar(df_top_20, x='language', y='teacher_id', title='Number of Teachers by Language Taught (Top 20)', labels={'teacher_id': 'Number of Teachers', 'language': 'Language'})
fig.show()

What is the mean hourly price for each of languages retrieved?

In [15]:
get_all_df(dataframe_list)

<class 'pandas.DataFrame'>
RangeIndex: 10470 entries, 0 to 10469
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              10470 non-null  int64
 1   nickname             10470 non-null  str
 2   is_tutor             10470 non-null  int64
 3   is_pro               10470 non-null  int64
 4   origin_country_id    10470 non-null  str
 5   living_country_id    10470 non-null  str
 6   origin_city_id       10470 non-null  str
 7   origin_city_name     10470 non-null  str
 8   living_city_id       10470 non-null  str
 9   living_city_name     10470 non-null  str
 10  timezone             10470 non-null  str
 11  trial_length         10470 non-null  int64
 12  has_trial            10470 non-null  int64
 13  trial_price          10470 non-null  int64
 14  min_price            10470 non-null  int64
 15  trial_session_count  10470 non-null  int64
 16  has_beginner_course  10470 non-null  int64
dtypes: int64(9), str(8)
memory usage: 1.9 MB

<class 'pandas.DataFrame'>
RangeIndex: 10470 entries, 0 to 10469
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10470 non-null  int64
 1   finished_session  10470 non-null  int64
 2   response_rate     10470 non-null  float64
 3   attendance_rate   10470 non-null  float64
dtypes: float64(2), int64(2)
memory usage: 327.3 KB

<class 'pandas.DataFrame'>
RangeIndex: 39035 entries, 0 to 39034
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             39035 non-null  int64
 1   teacher_id     39035 non-null  int64
 2   language       39035 non-null  str
 3   title          39035 non-null  str
 4   session_price  39035 non-null  int64
 5   student_count  39035 non-null  int64
 6   session_count  39035 non-null  int64
 7   has_package    39035 non-null  int64
dtypes: int64(6), str(2)
memory usage: 4.5 MB

<class 'pandas.DataFrame'>
RangeIndex: 215827 entries, 0 to 215826
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   package_price    215827 non-null  int64
 1   session_price    215827 non-null  int64
 2   course_id        215827 non-null  int64
 3   package_length   215827 non-null  int64
 4   session_length   215827 non-null  int64
 5   course_price_id  215827 non-null  int64
dtypes: int64(6)
memory usage: 9.9 MB

<class 'pandas.DataFrame'>
RangeIndex: 29185 entries, 0 to 29184
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user_id   29185 non-null  int64
 1   language  29185 non-null  int64
dtypes: int64(2)
memory usage: 456.1 KB

<class 'pandas.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       210 non-null    str
dtypes: str(1)
memory usage: 3.7 KB

In [16]:
average_price = {}
median_price = {}

for language in retrieved_languages:
    median = df_pro_course[df_pro_course['language'] == language]['session_price'].median()
    mean = df_pro_course[df_pro_course['language'] == language]['session_price'].mean()
    average_price[language] = round(mean)/100
    median_price[language] = round(median)/100

df_average_price = pd.DataFrame.from_dict(average_price, orient="index", columns=["Average Price"])
df_average_price
fig = px.bar(df_average_price, y='Average Price')
fig.show()

In [17]:
df_median_price = pd.DataFrame.from_dict(median_price, orient="index", columns=["Median Price"])
df_median_price

          Median Price
english           22.0
chinese           22.0
french            25.0
spanish           18.0
japanese          24.0
italian           25.0
german            32.0
korean            21.0

In [18]:

fig = px.bar(df_median_price, y='Median Price')
fig.show()

In [19]:
df_pro_course[df_pro_course['id'] == 290784]

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
39030,290784,31481128,french,🗣️ Natural French Conversation: Speak easily !,700,0,0,1

In [20]:
df_price_list[df_price_list['session_length'] == 4]

,package_price,session_price,course_id,package_length,session_length,course_price_id
2,20900,2300,946,10,4,823
5,30500,3200,4042,10,4,3934
7,30900,3400,5620,10,4,5525
8,20900,2300,5779,10,4,5686
13,15000,1590,8775,10,4,8797
...,...,...,...,...,...,...
215805,55000,4000,290796,15,4,1084922
215809,70000,4000,290796,20,4,1084926
215810,38000,4000,290796,10,4,1084927
215825,59999,7498,87801,10,4,1085029
215826,84999,7498,87801,15,4,1085030

How many teachers teach multiple languages?

In [21]:
df_multiple_languages = df_pro_course.groupby(['teacher_id','language']).count().reset_index()
df_multiple_languages = df_multiple_languages[['teacher_id', 'language']].groupby('teacher_id').count()
df_multiple_languages = df_multiple_languages.reset_index()
count = len(df_multiple_languages[df_multiple_languages['language'] > 1])
print(f'{round(count/len(df_multiple_languages) * 100, 2)}% of teachers teach multiple languages')

22.37% of teachers teach multiple languages

Among the teachers that speak multiple languages, what are the two languages that a single teacher is most likely to teach?

In [22]:
df_top_8_languages = df_teacher_language_count.sort_values('teacher_id', ascending=False).head(8).reset_index()
row_list = df_top_8_languages['language'].values.tolist()
row_list

['english',
 'spanish',
 'french',
 'japanese',
 'chinese',
 'italian',
 'german',
 'korean']

In [23]:
df_multiple_languages[df_multiple_languages['language'] > 1]

       teacher_id  language
5          222305         5
6          249152         2
13         399468         2
15         436016         2
17         468130         2
...           ...       ...
10391    31822868         2
10393    31823132         2
10396    31826538         2
10409    31913530         2
10465    32167939         2

[2342 rows x 2 columns]

In [26]:
df_multiple_languages_original = df_pro_course.groupby(['teacher_id','language']).count().reset_index()
df_multiple_languages_original = df_multiple_languages_original[['teacher_id', 'language']]
df_multiple_languages_original

       teacher_id       language
0           55502        chinese
1          113638        chinese
2          114708        chinese
3          132815         korean
4          148092        spanish
...           ...            ...
13696    32167939  haitiancreole
13697    32168520        english
13698    32169200        english
13699    32169731        english
13700    32171759         french

[13701 rows x 2 columns]

In [48]:
df_multiple_dummies = pd.get_dummies(df_multiple_languages_original, columns=['language'])
df_multiple_dummies = df_multiple_dummies.groupby('teacher_id').max().reset_index()
df_multiple_dummies_8 = df_multiple_dummies[['teacher_id', 'language_english', 'language_chinese', 'language_french', 'language_spanish', 'language_german', 'language_japanese', 'language_korean', 'language_italian']]
df_english = df_multiple_dummies_8[df_multiple_dummies_8['language_english'] == True]
df_english_sum = df_english[['language_chinese', 'language_french', 'language_spanish', 'language_german', 'language_japanese', 'language_korean', 'language_italian']].sum().reset_index()
df_english_sum = df_english_sum.rename(columns={'index': 'language', 0: 'count'})
df_english_sum

            language  count
0   language_chinese    118
1    language_french    238
2   language_spanish    368
3    language_german    118
4  language_japanese     48
5    language_korean     36
6   language_italian    144

In [50]:
fig = px.bar(df_english_sum, x='language', y='count', title='Count of English Teachers that also teach other popular languages', labels={'count': 'Number of Teachers', 'language': 'Language'})
fig.show()