In [1]:
import pandas as pd
import json
from datetime import datetime
from zoneinfo import ZoneInfo

Check duplicates for User and Course Info

In [ ]:
with open('../data_extraction/user_course_info.json', 'r') as file:
    user_course_info_check = json.load(file)

df_user_course_info_check = pd.DataFrame(user_course_info_check)

In [3]:
df_user_course_info_check

,user_id,nickname,is_tutor,is_pro,origin_country_id,living_country_id,origin_city_id,origin_city_name,living_city_id,living_city_name,timezone,trial_length,has_trial,trial_price,min_price,trial_session_count,has_beginner_course
0,5467830,⭐Learn with Kim/Kin,1,0,CN,KR,CN00001,Shanghai,KR00001,Seoul,Asia/Shanghai,2,0,1988,500,562,1
1,11401921,Teacher Emee,1,0,PH,PH,PH00000,Other,PH00000,Other,Asia/Manila,2,0,500,500,186,1
2,9627036,Shyam Syangtan,1,0,IN,IN,IN00771,Sonipat,IN00231,Delhi,Asia/Kolkata,2,0,700,500,1366,1
3,5787377,Kimi(y)a 👩🏻🎓❤️,1,0,IR,IT,IR00016,Tabriz,IT00016,Turin,Asia/Tehran,2,0,799,500,384,1
4,9934037,Anne Rola,1,0,PH,PH,PH00000,Other,PH00236,Tacloban,Asia/Shanghai,2,0,500,500,115,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11164,8392625,Yunhee Jung,1,0,US,US,US00346,East Los Angeles,US00346,East Los Angeles,America/Los_Angeles,2,0,1500,5000,0,1
11165,9170372,Hera 최해라,1,1,KR,GB,KR00166,Gunpo,GB00001,London,Europe/London,2,0,1500,5000,291,1
11166,23372570,MyKoreanTeacherDan,0,1,NZ,NZ,NZ00000,Other,NZ00001,Auckland,Pacific/Auckland,3,0,3500,5000,0,0
11167,8296973,Leeji 리지(Ji Eun Lee),0,1,KR,DE,KR00001,Seoul,DE00101,Karlsruhe,Europe/Berlin,2,0,2000,5000,0,1
11168,21737274,Julia,1,0,KR,US,KR00000,Other,US00831,New York,Asia/Seoul,2,0,2800,5600,0,1

In [4]:
list(df_user_course_info_check.columns)

['user_id',
 'nickname',
 'is_tutor',
 'is_pro',
 'origin_country_id',
 'living_country_id',
 'origin_city_id',
 'origin_city_name',
 'living_city_id',
 'living_city_name',
 'timezone',
 'trial_length',
 'has_trial',
 'trial_price',
 'min_price',
 'trial_session_count',
 'has_beginner_course']

In [5]:
columns_user = ['user_id',
 'nickname',
 'is_tutor',
 'is_pro',
 'origin_country_id',
 'living_country_id',
 'origin_city_id',
 'origin_city_name',
 'living_city_id',
 'living_city_name',
 'timezone']

Check if there are users that appear more than twice

In [6]:
df_user_dup = df_user_course_info_check[df_user_course_info_check[['user_id', 'nickname']].duplicated(keep=False)]

In [7]:
df_unique = df_user_dup.groupby(['user_id', 'nickname']).count()
# df_unique = df_unique.reset_index(names='user_id')

In [8]:
df_unique

,,is_tutor,is_pro,origin_country_id,living_country_id,origin_city_id,origin_city_name,living_city_id,living_city_name,timezone,trial_length,has_trial,trial_price,min_price,trial_session_count,has_beginner_course
user_id,nickname,,,,,,,,,,,,,,,
495195,Maria Exam Work etc,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
707465,Andrea,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
719539,Teddy,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
745006,Rose,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
755999,Tati,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30946403,Edoardo,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
31046452,Kohl Sandra,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
31264233,Valentin Bétourné,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
31265601,Niko,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
31822868,Nikki Gevana,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

Users that have multiple entries of the same user_id and same nickname are removed.\
The latest one is kept because it means that they have updated some of their personal information

In [9]:
df_user_course_sorted = df_user_course_info_check.sort_values('user_id')
df_no_dup_id_nickname = df_user_course_sorted.drop_duplicates(subset=['user_id', 'nickname'], keep='last')
df_no_dup_id_nickname

,user_id,nickname,is_tutor,is_pro,origin_country_id,living_country_id,origin_city_id,origin_city_name,living_city_id,living_city_name,timezone,trial_length,has_trial,trial_price,min_price,trial_session_count,has_beginner_course
5833,55502,Micky Mick,1,0,CN,CN,CN00226,Fushun,CN00006,Beijing,Asia/Shanghai,2,0,1000,2000,97,1
5929,113638,Xin,1,1,CN,CA,,,CA00006,Montreal,America/Toronto,2,0,999,2500,227,0
5642,114708,Amy (Féng lǎoshī）,0,1,CN,CN,CN00201,Jilin,CN00201,Jilin,Asia/Shanghai,2,0,500,1990,6,1
10791,132815,Julie 줄리,1,0,KR,KR,KR00001,Seoul,KR00001,Seoul,Asia/Seoul,2,0,750,1500,0,1
7858,148092,Jhon Jairo,0,1,CO,CO,CO00101,Armenia,CO00006,Medellin,America/Bogota,2,0,1000,2500,182,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4655,32167939,Andrele,1,0,CA,CA,CA00000,Other,CA00000,Other,America/Toronto,2,0,1000,2000,3,1
220,32168520,Daphne👩🏫🌸💗,1,0,PH,PH,PH00141,Baguio,PH00000,Other,Asia/Manila,3,0,500,700,0,0
4152,32169200,Davide Castellani,1,0,IT,IT,IT00000,Other,IT00000,Other,Europe/Rome,4,0,1400,1400,0,1
4150,32169731,FelixRansford,1,0,GB,ES,GB00281,Exeter,ES00131,Jerez de la Frontera,Europe/Madrid,2,0,600,1400,0,0
4439,32171759,Roselene Noel,1,0,HT,DO,HT00000,Other,DO00000,Other,America/Santo_Domingo,2,0,500,1200,0,0

In [10]:
# diff = df_unique.compare(df_unique_all)

In [11]:
user_course_info_cleaned = df_no_dup_id_nickname.to_dict(orient='records')

In [12]:
user_course_info_cleaned

[{'user_id': 55502,
  'nickname': 'Micky Mick',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'CN',
  'living_country_id': 'CN',
  'origin_city_id': 'CN00226',
  'origin_city_name': 'Fushun',
  'living_city_id': 'CN00006',
  'living_city_name': 'Beijing',
  'timezone': 'Asia/Shanghai',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 2000,
  'trial_session_count': 97,
  'has_beginner_course': 1},
 {'user_id': 113638,
  'nickname': 'Xin',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'CN',
  'living_country_id': 'CA',
  'origin_city_id': '',
  'origin_city_name': '',
  'living_city_id': 'CA00006',
  'living_city_name': 'Montreal',
  'timezone': 'America/Toronto',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 999,
  'min_price': 2500,
  'trial_session_count': 227,
  'has_beginner_course': 0},
 {'user_id': 114708,
  'nickname': 'Amy (Féng lǎoshī）',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'CN',
  'living_country_id': 'CN',
  'origin_city_id': 'CN00201',
  'origin_city_name': 'Jilin',
  'living_city_id': 'CN00201',
  'living_city_name': 'Jilin',
  'timezone': 'Asia/Shanghai',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 500,
  'min_price': 1990,
  'trial_session_count': 6,
  'has_beginner_course': 1},
 {'user_id': 132815,
  'nickname': 'Julie 줄리',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'KR',
  'living_country_id': 'KR',
  'origin_city_id': 'KR00001',
  'origin_city_name': 'Seoul',
  'living_city_id': 'KR00001',
  'living_city_name': 'Seoul',
  'timezone': 'Asia/Seoul',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 750,
  'min_price': 1500,
  'trial_session_count': 0,
  'has_beginner_course': 1},
 {'user_id': 148092,
  'nickname': 'Jhon Jairo',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'CO',
  'living_country_id': 'CO',
  'origin_city_id': 'CO00101',
  'origin_city_name': 'Armenia',
  'living_city_id': 'CO00006',
  'living_city_name': 'Medellin',
  'timezone': 'America/Bogota',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 2500,
  'trial_session_count': 182,
  'has_beginner_course': 0},
 {'user_id': 222305,
  'nickname': 'Adriano teacher',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'BR',
  'living_country_id': 'BR',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'ZZ00000',
  'living_city_name': 'Other',
  'timezone': 'America/Sao_Paulo',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 799,
  'min_price': 1499,
  'trial_session_count': 1378,
  'has_beginner_course': 0},
 {'user_id': 249152,
  'nickname': 'CeciliaStockholm',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'AR',
  'living_country_id': 'SE',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'SE00061',
  'living_city_name': 'Boras',
  'timezone': 'Europe/Stockholm',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 800,
  'min_price': 1800,
  'trial_session_count': 70,
  'has_beginner_course': 0},
 {'user_id': 259649,
  'nickname': 'Ally',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'CN',
  'living_country_id': 'CN',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'ZZ00000',
  'living_city_name': 'Other',
  'timezone': 'Asia/Shanghai',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 690,
  'min_price': 1190,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 291538,
  'nickname': 'RYOTA',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'JP',
  'living_country_id': 'JP',
  'origin_city_id': 'JP00011',
  'origin_city_name': 'Osaka',
  'living_city_id': 'JP00001',
  'living_city_name': 'Tokyo',
  'timezone': 'Asia/Phnom_Penh',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 650,
  'min_price': 2480,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 316582,
  'nickname': 'CLAU📚S☧anish📖💛💙❤',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'VE',
  'living_country_id': 'VE',
  'origin_city_id': 'VE00016',
  'origin_city_name': 'Barquisimeto',
  'living_city_id': 'VE00016',
  'living_city_name': 'Barquisimeto',
  'timezone': 'America/Caracas',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 500,
  'min_price': 1000,
  'trial_session_count': 148,
  'has_beginner_course': 1},
 {'user_id': 346460,
  'nickname': 'Rose',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'US',
  'living_country_id': 'CZ',
  'origin_city_id': 'US01176',
  'origin_city_name': 'Spokane',
  'living_city_id': 'CZ00000',
  'living_city_name': 'Other',
  'timezone': 'Europe/Berlin',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 1700,
  'trial_session_count': 175,
  'has_beginner_course': 0},
 {'user_id': 355886,
  'nickname': 'Laya',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'VE',
  'living_country_id': 'VE',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'ZZ00000',
  'living_city_name': 'Other',
  'timezone': 'America/Caracas',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 500,
  'min_price': 750,
  'trial_session_count': 142,
  'has_beginner_course': 1},
 {'user_id': 368484,
  'nickname': 'Angeles',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'ES',
  'living_country_id': 'ES',
  'origin_city_id': 'ES00181',
  'origin_city_name': 'Burgos',
  'living_city_id': 'ES00181',
  'living_city_name': 'Burgos',
  'timezone': 'Europe/Madrid',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 2100,
  'trial_session_count': 91,
  'has_beginner_course': 0},
 {'user_id': 399468,
  'nickname': 'Tati Voronkoff',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'BR',
  'living_country_id': 'BR',
  'origin_city_id': 'BR00081',
  'origin_city_name': 'Maceio',
  'living_city_id': 'BR00081',
  'living_city_name': 'Maceio',
  'timezone': 'America/Recife',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 800,
  'min_price': 1500,
  'trial_session_count': 109,
  'has_beginner_course': 0},
 {'user_id': 426279,
  'nickname': 'College&Career-Troy',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'US',
  'living_country_id': 'US',
  'origin_city_id': 'US01116',
  'origin_city_name': 'San Jose',
  'living_city_id': 'US01116',
  'living_city_name': 'San Jose',
  'timezone': 'America/Los_Angeles',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 4100,
  'min_price': 7500,
  'trial_session_count': 121,
  'has_beginner_course': 0},
 {'user_id': 436016,
  'nickname': 'chinalily',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'CN',
  'living_country_id': 'CN',
  'origin_city_id': 'CN00081',
  'origin_city_name': 'Dalian',
  'living_city_id': 'CN00081',
  'living_city_name': 'Dalian',
  'timezone': 'Asia/Shanghai',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 700,
  'min_price': 1300,
  'trial_session_count': 0,
  'has_beginner_course': 1},
 {'user_id': 463477,
  'nickname': 'Beth',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'GB',
  'living_country_id': 'ES',
  'origin_city_id': 'GB00001',
  'origin_city_name': 'London',
  'living_city_id': 'ES00011',
  'living_city_name': 'Valencia',
  'timezone': 'Europe/Paris',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 2000,
  'min_price': 3000,
  'trial_session_count': 156,
  'has_beginner_course': 1},
 {'user_id': 468130,
  'nickname': 'Petr',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'RU',
  'living_country_id': 'RU',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'RU00001',
  'living_city_name': 'Moscow',
  'timezone': 'Europe/Moscow',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1200,
  'min_price': 2100,
  'trial_session_count': 106,
  'has_beginner_course': 0},
 {'user_id': 477566,
  'nickname': 'Annie',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'JP',
  'living_country_id': 'JP',
  'origin_city_id': '',
  'origin_city_name': '',
  'living_city_id': 'JP00166',
  'living_city_name': 'Oita',
  'timezone': 'Asia/Tokyo',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 2000,
  'trial_session_count': 1444,
  'has_beginner_course': 1},
 {'user_id': 483024,
  'nickname': 'Brad C',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'US',
  'living_country_id': 'US',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'US00961',
  'living_city_name': 'Pittsburgh',
  'timezone': 'Europe/London',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 2000,
  'min_price': 5500,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 484682,
  'nickname': 'Rick',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'CA',
  'living_country_id': 'US',
  'origin_city_id': 'CA00001',
  'origin_city_name': 'Toronto',
  'living_city_id': 'US00136',
  'living_city_name': 'Boise City',
  'timezone': 'America/Denver',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 500,
  'min_price': 1600,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 495195,
  'nickname': 'Maria Exam Work etc',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'RU',
  'living_country_id': 'RU',
  'origin_city_id': 'RU00001',
  'origin_city_name': 'Moscow',
  'living_city_id': 'RU00001',
  'living_city_name': 'Moscow',
  'timezone': 'Europe/Moscow',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 1400,
  'trial_session_count': 440,
  'has_beginner_course': 0},
 {'user_id': 499227,
  'nickname': 'Elena A',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'BG',
  'living_country_id': 'BG',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'ZZ00000',
  'living_city_name': 'Other',
  'timezone': 'Europe/Bucharest',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1400,
  'min_price': 3300,
  'trial_session_count': 228,
  'has_beginner_course': 1},
 {'user_id': 502096,
  'nickname': '⭐️ Natasha ⭐️',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'RS',
  'living_country_id': 'IT',
  'origin_city_id': 'RS00001',
  'origin_city_name': 'Belgrade',
  'living_city_id': 'IT00041',
  'living_city_name': 'Bari',
  'timezone': 'Europe/San_Marino',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 2300,
  'trial_session_count': 213,
  'has_beginner_course': 0},
 {'user_id': 514826,
  'nickname': 'Jon',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'GB',
  'living_country_id': 'GB',
  'origin_city_id': 'GB00241',
  'origin_city_name': 'Brighton',
  'living_city_id': 'GB00001',
  'living_city_name': 'London',
  'timezone': 'Europe/London',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1600,
  'min_price': 2700,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 515185,
  'nickname': 'Jairo Pérez',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'CO',
  'living_country_id': 'CO',
  'origin_city_id': 'CO00001',
  'origin_city_name': 'Bogota',
  'living_city_id': 'CO00216',
  'living_city_name': 'Duitama',
  'timezone': 'America/Bogota',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 500,
  'min_price': 1290,
  'trial_session_count': 104,
  'has_beginner_course': 0},
 {'user_id': 516278,
  'nickname': 'Ahiru',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'DE',
  'living_country_id': 'TH',
  'origin_city_id': 'DE00116',
  'origin_city_name': 'Gelsenkirchen',
  'living_city_id': 'TH00001',
  'living_city_name': 'Bangkok',
  'timezone': 'Asia/Bangkok',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 500,
  'min_price': 2490,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 517538,
  'nickname': 'Carla',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'BO',
  'living_country_id': 'BO',
  'origin_city_id': 'BO00011',
  'origin_city_name': 'La Paz',
  'living_city_id': 'BO00011',
  'living_city_name': 'La Paz',
  'timezone': 'America/La_Paz',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 2000,
  'trial_session_count': 734,
  'has_beginner_course': 0},
 {'user_id': 530071,
  'nickname': 'MatthieuDX',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'FR',
  'living_country_id': 'PT',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'PT00001',
  'living_city_name': 'Lisbon',
  'timezone': 'Europe/Lisbon',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 990,
  'min_price': 3000,
  'trial_session_count': 111,
  'has_beginner_course': 0},
 {'user_id': 535501,
  'nickname': 'Carlos Gomez',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'CR',
  'living_country_id': 'CH',
  'origin_city_id': 'CR00046',
  'origin_city_name': 'Paraiso',
  'living_city_id': 'CH00021',
  'living_city_name': 'Lausanne',
  'timezone': 'Europe/Zurich',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 3100,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 538395,
  'nickname': 'eric',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'JP',
  'living_country_id': 'JP',
  'origin_city_id': 'JP00001',
  'origin_city_name': 'Tokyo',
  'living_city_id': 'JP00001',
  'living_city_name': 'Tokyo',
  'timezone': 'Asia/Tokyo',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 700,
  'min_price': 1600,
  'trial_session_count': 215,
  'has_beginner_course': 1},
 {'user_id': 543974,
  'nickname': 'RiverLiu',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'CN',
  'living_country_id': 'CN',
  'origin_city_id': 'CN00376',
  'origin_city_name': 'Zhanjiang',
  'living_city_id': 'CN00376',
  'living_city_name': 'Zhanjiang',
  'timezone': 'Asia/Shanghai',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 500,
  'min_price': 1000,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 544865,
  'nickname': 'Nalini',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'IN',
  'living_country_id': 'IT',
  'origin_city_id': 'IN00231',
  'origin_city_name': 'Delhi',
  'living_city_id': 'IT00206',
  'living_city_name': 'Novara',
  'timezone': 'Europe/Rome',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 800,
  'min_price': 1800,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 552716,
  'nickname': 'Daria',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'RU',
  'living_country_id': 'IT',
  'origin_city_id': 'RU00006',
  'origin_city_name': 'St. Petersburg',
  'living_city_id': 'IT00006',
  'living_city_name': 'Milan',
  'timezone': 'Europe/Berlin',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 600,
  'min_price': 2600,
  'trial_session_count': 123,
  'has_beginner_course': 1},
 {'user_id': 570744,
  'nickname': 'Aura\u3000オーラ',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'US',
  'living_country_id': 'US',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'ZZ00000',
  'living_city_name': 'Other',
  'timezone': 'America/Chicago',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 1700,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 591602,
  'nickname': 'Koichi Sembu',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'JP',
  'living_country_id': 'JP',
  'origin_city_id': 'JP00051',
  'origin_city_name': 'Hiroshima',
  'living_city_id': 'JP00486',
  'living_city_name': 'Kasukabe',
  'timezone': 'Asia/Tokyo',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1300,
  'min_price': 2000,
  'trial_session_count': 697,
  'has_beginner_course': 1},
 {'user_id': 595157,
  'nickname': 'Consuelo',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'ES',
  'living_country_id': 'ES',
  'origin_city_id': 'ES00001',
  'origin_city_name': 'Madrid',
  'living_city_id': 'ES00001',
  'living_city_name': 'Madrid',
  'timezone': 'Europe/Berlin',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1500,
  'min_price': 2000,
  'trial_session_count': 230,
  'has_beginner_course': 0},
 {'user_id': 596847,
  'nickname': 'Claire',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'GB',
  'living_country_id': 'GB',
  'origin_city_id': 'GB00111',
  'origin_city_name': 'Newcastle upon Tyne',
  'living_city_id': 'GB00000',
  'living_city_name': 'Other',
  'timezone': 'Europe/London',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1400,
  'min_price': 2500,
  'trial_session_count': 220,
  'has_beginner_course': 0},
 {'user_id': 600465,
  'nickname': 'Tarık',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'TR',
  'living_country_id': 'TR',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'TR00000',
  'living_city_name': 'Other',
  'timezone': 'Europe/Paris',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1800,
  'min_price': 3700,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 600986,
  'nickname': 'Tomaliko',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'JP',
  'living_country_id': 'RS',
  'origin_city_id': 'JP00036',
  'origin_city_name': 'Fukuoka',
  'living_city_id': 'RS00006',
  'living_city_name': 'Novi Sad',
  'timezone': 'Europe/Belgrade',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 700,
  'min_price': 1500,
  'trial_session_count': 725,
  'has_beginner_course': 0},
 {'user_id': 602226,
  'nickname': 'Matt (Gad Academy)',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'GB',
  'living_country_id': 'EG',
  'origin_city_id': 'GB00001',
  'origin_city_name': 'London',
  'living_city_id': 'EG00001',
  'living_city_name': 'Cairo',
  'timezone': 'Africa/Cairo',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1250,
  'min_price': 3000,
  'trial_session_count': 1321,
  'has_beginner_course': 0},
 {'user_id': 612092,
  'nickname': 'Jackson Bagatoli',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'BR',
  'living_country_id': 'BR',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'BR00241',
  'living_city_name': 'Florianopolis',
  'timezone': 'America/Sao_Paulo',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 500,
  'min_price': 1700,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 614209,
  'nickname': 'Pavel Lyashkov',
  'is_tutor': 1,
  'is_pro': 0,
  'origin_country_id': 'RU',
  'living_country_id': 'AM',
  'origin_city_id': 'RU00000',
  'origin_city_name': 'Other',
  'living_city_id': 'AM00000',
  'living_city_name': 'Other',
  'timezone': 'Europe/Moscow',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 1000,
  'min_price': 3000,
  'trial_session_count': 0,
  'has_beginner_course': 0},
 {'user_id': 644741,
  'nickname': '🎓Kathy',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'DE',
  'living_country_id': 'BG',
  'origin_city_id': 'DE00061',
  'origin_city_name': 'Dresden',
  'living_city_id': 'BG00001',
  'living_city_name': 'Sofia',
  'timezone': 'Europe/Kiev',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 900,
  'min_price': 3900,
  'trial_session_count': 354,
  'has_beginner_course': 0},
 {'user_id': 652005,
  'nickname': 'Scarlet  Lorraine',
  'is_tutor': 1,
  'is_pro': 1,
  'origin_country_id': 'ZZ',
  'living_country_id': 'US',
  'origin_city_id': 'ZZ00000',
  'origin_city_name': 'Other',
  'living_city_id': 'US01071',
  'living_city_name': 'Sacramento',
  'timezone': 'America/Los_Angeles',
  'trial_length': 2,
  'has_trial': 0,
  'trial_price': 700,
  'min_price': 1800,
  'trial_session_count': 782,
  'has_beginner_course': 1},
 {'user_id': 658229,
  'nickname': 'Tom Emery',
  'is_tutor': 0,
  'is_pro': 1,
  'origin_country_id': 'GB',
  'living_country_id': 'GB',
  'origin_city_id': 'GB00166',
  'origin_city_name': 'Bournemouth',
  'living_city_id': 'GB00166',
  'living_city_name': 'Bournemouth',
  'timezone': 'Europe/Budapest',

Check if 'has_trial' column in the users and trial table indicates 0 but trial count is more than 1.\
From the code block below, all users have the column 'has_trial' as 0.\
This means that if the trial price is greater than 0 or the trial session count is greater than 0, it does not matter what the 'has_trial' indicates\
Hence the has_trial column should not be used.

In [75]:
df_no_dup_id_nickname[df_no_dup_id_nickname['has_trial'] == 0].count()

user_id                10470
nickname               10470
is_tutor               10470
is_pro                 10470
origin_country_id      10470
living_country_id      10470
origin_city_id         10470
origin_city_name       10470
living_city_id         10470
living_city_name       10470
timezone               10470
trial_length           10470
has_trial              10470
trial_price            10470
min_price              10470
trial_session_count    10470
has_beginner_course    10470
dtype: int64

In [14]:
with open('./user_course_info_cleaned.json', 'w') as file:
        json.dump(user_course_info_cleaned, file, indent=4)

In [13]:
df_no_dup_id_nickname[df_no_dup_id_nickname['user_id'] == 1689306]

,user_id,nickname,is_tutor,is_pro,origin_country_id,living_country_id,origin_city_id,origin_city_name,living_city_id,living_city_name,timezone,trial_length,has_trial,trial_price,min_price,trial_session_count,has_beginner_course
5228,1689306,Cristina Domènech,0,1,ES,NL,ES00006,Barcelona,NL00111,Leiden,Europe/Amsterdam,2,0,4600,7400,1116,1

Check duplicates in teacher_stats

In [14]:
with open('../data_extraction/teacher_stats.json', 'r') as file:
    teacher_stats_check = json.load(file)

df_teacher_statscheck = pd.DataFrame(teacher_stats_check)

In [22]:
df_teacher_statscheck

        user_id  finished_session  response_rate  attendance_rate
0       5467830              4220           1.00             1.00
1      11401921              7443           1.00             1.00
2       9627036              6346           1.00             1.00
3       5787377              5007           1.00             1.00
4       9934037              2664           1.00             0.99
...         ...               ...            ...              ...
11032   8712350              1143           1.00             1.00
11033   8392625               364           0.98             0.99
11034   9170372              5033           1.00             1.00
11035  23372570                12           1.00             1.00
11036   8296973              1287           1.00             1.00

[11037 rows x 4 columns]

In [15]:
df_teacher_stats_dup = df_teacher_statscheck[df_teacher_statscheck[['user_id']].duplicated(keep=False)]

In [16]:
df_teacher_stats_dup

        user_id  finished_session  response_rate  attendance_rate
0       5467830              4220           1.00             1.00
5       7023372              4547           1.00             1.00
76     28084220               269           1.00             1.00
93     10599672              1068           1.00             1.00
98      7603855               404           0.99             0.98
...         ...               ...            ...              ...
10945   3524894              7374           1.00             1.00
10951  11663378              1443           1.00             1.00
10952   5728578              4621           1.00             1.00
10956    815733              3168           0.99             1.00
10964  23907480              1021           1.00             1.00

[1122 rows x 4 columns]

In [17]:
df_teacher_stats_count = df_teacher_stats_dup.groupby('user_id').count()
df_teacher_stats_count

          finished_session  response_rate  attendance_rate
user_id
222305                   3              3                3
495195                   2              2                2
502096                   2              2                2
706352                   2              2                2
707465                   2              2                2
...                    ...            ...              ...
30739843                 2              2                2
30934061                 2              2                2
31068665                 2              2                2
31265601                 2              2                2
31823132                 2              2                2

[555 rows x 3 columns]

In [18]:
df_teacher_stats_count[df_teacher_stats_count['finished_session'] >= 4].count()

finished_session    0
response_rate       0
attendance_rate     0
dtype: int64

In [19]:
df_teacher_stats_sorted = df_teacher_statscheck.sort_values('user_id')
df_teacher_stats_no_dup = df_teacher_stats_sorted.drop_duplicates(subset=['user_id'], keep='last')
df_teacher_stats_no_dup

        user_id  finished_session  response_rate  attendance_rate
5838      55502              2689           1.00             1.00
5933     113638              8410           1.00             1.00
5648     114708                50           0.94             0.98
10675    132815              2046           1.00             1.00
7838     148092              4109           1.00             1.00
...         ...               ...            ...              ...
4659   32167939                 3           1.00             1.00
220    32168520                 1           1.00             1.00
4152   32169200                 0           0.00             0.00
4150   32169731                 0           0.00             0.00
4439   32171759                 0           0.00             0.00

[10470 rows x 4 columns]

In [20]:
df_teacher_statscheck
df_teacher_statscheck[df_teacher_statscheck['user_id'] == 1689306]

      user_id  finished_session  response_rate  attendance_rate
4077  1689306             15479            1.0              1.0
5247  1689306             15488            1.0              1.0

In [21]:
df_teacher_stats_no_dup[df_teacher_stats_no_dup['user_id'] == 1689306]

      user_id  finished_session  response_rate  attendance_rate
5247  1689306             15488            1.0              1.0

In [22]:
teacher_stats_cleaned = df_teacher_stats_no_dup.to_dict(orient='records')

In [23]:
teacher_stats_cleaned

[{'user_id': 55502,
  'finished_session': 2689,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 113638,
  'finished_session': 8410,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 114708,
  'finished_session': 50,
  'response_rate': 0.94,
  'attendance_rate': 0.98},
 {'user_id': 132815,
  'finished_session': 2046,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 148092,
  'finished_session': 4109,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 222305,
  'finished_session': 14061,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 249152,
  'finished_session': 1249,
  'response_rate': 0.97,
  'attendance_rate': 0.99},
 {'user_id': 259649,
  'finished_session': 8798,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 291538,
  'finished_session': 2503,
  'response_rate': 0.98,
  'attendance_rate': 0.98},
 {'user_id': 316582,
  'finished_session': 5608,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 346460,
  'finished_session': 7171,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 355886,
  'finished_session': 6671,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 368484,
  'finished_session': 5397,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 399468,
  'finished_session': 3101,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 426279,
  'finished_session': 647,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 436016,
  'finished_session': 2288,
  'response_rate': 0.96,
  'attendance_rate': 0.99},
 {'user_id': 463477,
  'finished_session': 3028,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 468130,
  'finished_session': 3716,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 477566,
  'finished_session': 29983,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 483024,
  'finished_session': 1631,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 484682,
  'finished_session': 240,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 495195,
  'finished_session': 9568,
  'response_rate': 0.98,
  'attendance_rate': 1.0},
 {'user_id': 499227,
  'finished_session': 6720,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 502096,
  'finished_session': 3664,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 514826,
  'finished_session': 1090,
  'response_rate': 0.97,
  'attendance_rate': 1.0},
 {'user_id': 515185,
  'finished_session': 1556,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 516278,
  'finished_session': 4278,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 517538,
  'finished_session': 8492,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 530071,
  'finished_session': 3749,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 535501,
  'finished_session': 1522,
  'response_rate': 0.98,
  'attendance_rate': 1.0},
 {'user_id': 538395,
  'finished_session': 6329,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 543974,
  'finished_session': 134,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 544865,
  'finished_session': 1076,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 552716,
  'finished_session': 1649,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 570744,
  'finished_session': 5477,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 591602,
  'finished_session': 13736,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 595157,
  'finished_session': 5846,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 596847,
  'finished_session': 7097,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 600465,
  'finished_session': 8172,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 600986,
  'finished_session': 7106,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 602226,
  'finished_session': 16741,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 612092,
  'finished_session': 5751,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 614209,
  'finished_session': 171,
  'response_rate': 0.96,
  'attendance_rate': 1.0},
 {'user_id': 644741,
  'finished_session': 8148,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 652005,
  'finished_session': 24406,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 658229,
  'finished_session': 11018,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 663702,
  'finished_session': 4302,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 682108,
  'finished_session': 7140,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 687031,
  'finished_session': 25064,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 691975,
  'finished_session': 966,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 706352,
  'finished_session': 6136,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 707465,
  'finished_session': 10064,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 719539,
  'finished_session': 819,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 738970,
  'finished_session': 3516,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 740680,
  'finished_session': 7241,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 745006,
  'finished_session': 11668,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 750834,
  'finished_session': 423,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 754436,
  'finished_session': 5843,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 754979,
  'finished_session': 5097,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 755192,
  'finished_session': 3648,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 755999,
  'finished_session': 5681,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 774968,
  'finished_session': 13036,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 792488,
  'finished_session': 2294,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 795706,
  'finished_session': 3102,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 797413,
  'finished_session': 4516,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 799220,
  'finished_session': 4241,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 808057,
  'finished_session': 672,
  'response_rate': 0.98,
  'attendance_rate': 0.98},
 {'user_id': 811320,
  'finished_session': 7682,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 814956,
  'finished_session': 1351,
  'response_rate': 0.98,
  'attendance_rate': 0.98},
 {'user_id': 815733,
  'finished_session': 3167,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 818089,
  'finished_session': 2935,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 825851,
  'finished_session': 3934,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 830828,
  'finished_session': 12,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 835769,
  'finished_session': 5392,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 836912,
  'finished_session': 6247,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 847273,
  'finished_session': 3415,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 850398,
  'finished_session': 4690,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 855323,
  'finished_session': 19488,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 864873,
  'finished_session': 5518,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 867550,
  'finished_session': 3380,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 869515,
  'finished_session': 3277,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 870419,
  'finished_session': 2663,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 878142,
  'finished_session': 2351,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 879316,
  'finished_session': 2782,
  'response_rate': 0.99,
  'attendance_rate': 0.97},
 {'user_id': 880215,
  'finished_session': 5139,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 880520,
  'finished_session': 4286,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 882889,
  'finished_session': 3523,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 889879,
  'finished_session': 2992,
  'response_rate': 0.97,
  'attendance_rate': 0.99},
 {'user_id': 890253,
  'finished_session': 2552,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 896917,
  'finished_session': 3792,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 897681,
  'finished_session': 836,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 897702,
  'finished_session': 3123,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 901015,
  'finished_session': 1736,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 902591,
  'finished_session': 2823,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 904516,
  'finished_session': 3749,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 904931,
  'finished_session': 9579,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 913791,
  'finished_session': 750,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 916033,
  'finished_session': 3687,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 931481,
  'finished_session': 2089,
  'response_rate': 0.97,
  'attendance_rate': 1.0},
 {'user_id': 934703,
  'finished_session': 1873,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 938609,
  'finished_session': 59,
  'response_rate': 1.0,
  'attendance_rate': 0.98},
 {'user_id': 939454,
  'finished_session': 3909,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 939984,
  'finished_session': 2335,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 943419,
  'finished_session': 15003,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 945406,
  'finished_session': 2139,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 948628,
  'finished_session': 8019,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 949187,
  'finished_session': 5498,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 953117,
  'finished_session': 9754,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 953599,
  'finished_session': 3496,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 954568,
  'finished_session': 2914,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 961354,
  'finished_session': 13760,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 962859,
  'finished_session': 12821,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 963562,
  'finished_session': 8906,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 972313,
  'finished_session': 21280,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 980661,
  'finished_session': 1266,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 982054,
  'finished_session': 849,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 985410,
  'finished_session': 1529,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 986470,
  'finished_session': 12965,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1002018,
  'finished_session': 959,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1026932,
  'finished_session': 3358,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1036773,
  'finished_session': 2807,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1039692,
  'finished_session': 447,
  'response_rate': 0.91,
  'attendance_rate': 0.99},
 {'user_id': 1040677,
  'finished_session': 1055,
  'response_rate': 0.96,
  'attendance_rate': 0.99},
 {'user_id': 1040742,
  'finished_session': 13989,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1050610,
  'finished_session': 588,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 1056206,
  'finished_session': 5046,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 1056370,
  'finished_session': 1928,
  'response_rate': 0.97,
  'attendance_rate': 0.99},
 {'user_id': 1060643,
  'finished_session': 1748,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1061830,
  'finished_session': 5273,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 1062013,
  'finished_session': 7083,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 1062384,
  'finished_session': 4426,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 1062695,
  'finished_session': 2904,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1062903,
  'finished_session': 3889,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1063266,
  'finished_session': 7542,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1063945,
  'finished_session': 4066,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1072323,
  'finished_session': 6386,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 1076546,
  'finished_session': 8841,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1078268,
  'finished_session': 8124,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 1080168,
  'finished_session': 1786,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1082056,
  'finished_session': 3392,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 1084019,
  'finished_session': 19889,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1085674,
  'finished_session': 8347,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1085740,
  'finished_session': 15352,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1090411,
  'finished_session': 4970,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1091784,
  'finished_session': 7309,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1105812,
  'finished_session': 8154,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 1108764,
  'finished_session': 990,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 1109648,
  'finished_session': 764,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1111764,
  'finished_session': 5133,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 1111875,
  'finished_session': 767,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1112442,
  'finished_session': 17703,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1113035,
  'finished_session': 7537,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1113086,
  'finished_session': 255,
  'response_rate': 0.98,
  'attendance_rate': 1.0},
 {'user_id': 1113206,
  'finished_session': 5817,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 1120125,
  'finished_session': 5430,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1121091,
  'finished_session': 19303,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1122137,
  'finished_session': 0,
  'response_rate': 0.0,
  'attendance_rate': 0.0},
 {'user_id': 1122140,
  'finished_session': 683,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 1132229,
  'finished_session': 3882,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 1132410,
  'finished_session': 2355,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1138564,
  'finished_session': 6227,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1139795,
  'finished_session': 79,
  'response_rate': 0.99,
  'attendance_rate': 0.96},
 {'user_id': 1140228,
  'finished_session': 865,
  'response_rate': 0.96,
  'attendance_rate': 0.98},
 {'user_id': 1140281,
  'finished_session': 2843,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1155571,
  'finished_session': 3127,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1155584,
  'finished_session': 12865,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1158637,
  'finished_session': 2106,
  'response_rate': 0.98,
  'attendance_rate': 1.0},
 {'user_id': 1159839,
  'finished_session': 17840,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1160526,
  'finished_session': 7036,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 1161780,
  'finished_session': 2504,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 1163821,
  'finished_session': 605,
  'response_rate': 0.98,
  'attendance_rate': 0.99},
 {'user_id': 1169629,
  'finished_session': 17752,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1175021,
  'finished_session': 2613,
  'response_rate': 1.0,
  'attendance_rate': 0.99},
 {'user_id': 1175046,
  'finished_session': 4106,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1179674,
  'finished_session': 546,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 1186052,
  'finished_session': 1617,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1186840,
  'finished_session': 1137,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 1195046,
  'finished_session': 2717,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 1195822,
  'finished_session': 3651,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1195901,
  'finished_session': 3341,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1203217,
  'finished_session': 1808,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1208054,
  'finished_session': 11251,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1209413,
  'finished_session': 3392,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1217763,
  'finished_session': 2735,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 1217972,
  'finished_session': 1659,
  'response_rate': 0.99,
  'attendance_rate': 1.0},
 {'user_id': 1221603,
  'finished_session': 4425,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1227283,
  'finished_session': 2964,
  'response_rate': 0.98,
  'attendance_rate': 1.0},
 {'user_id': 1227382,
  'finished_session': 11538,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1227745,
  'finished_session': 24052,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1232433,
  'finished_session': 2069,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1234543,
  'finished_session': 8827,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1235251,
  'finished_session': 1841,
  'response_rate': 0.99,
  'attendance_rate': 0.99},
 {'user_id': 1236479,
  'finished_session': 4186,
  'response_rate': 0.97,
  'attendance_rate': 0.99},
 {'user_id': 1237438,
  'finished_session': 436,
  'response_rate': 0.97,
  'attendance_rate': 0.99},
 {'user_id': 1242253,
  'finished_session': 5321,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1244149,
  'finished_session': 582,
  'response_rate': 0.97,
  'attendance_rate': 0.97},
 {'user_id': 1244200,
  'finished_session': 188,
  'response_rate': 1.0,
  'attendance_rate': 1.0},
 {'user_id': 1246494,
  'finished_session': 5994,
  'response_rate': 1.0,

In [24]:
with open('./teacher_stats_cleaned.json', 'w') as file:
        json.dump(teacher_stats_cleaned, file, indent=4)

Check if tutors have no pro course

In [25]:
with open('../data_extraction/pro_course.json', 'r') as file:
    pro_course_check = json.load(file)

df_pro_course_check = pd.DataFrame(pro_course_check)

In [26]:
df_pro_course_count = df_pro_course_check.groupby('teacher_id').count()
df_pro_course_count

,id,language,title,session_price,student_count,session_count,has_package
teacher_id,,,,,,,
55502,3,3,3,3,3,3,3
113638,4,4,4,4,4,4,4
114708,4,4,4,4,4,4,4
132815,5,5,5,5,5,5,5
148092,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...
32167939,2,2,2,2,2,2,2
32168520,3,3,3,3,3,3,3
32169200,1,1,1,1,1,1,1
32169731,1,1,1,1,1,1,1
32171759,1,1,1,1,1,1,1

In [27]:
df_pro_course_count[df_pro_course_count['id'] > 0]

,id,language,title,session_price,student_count,session_count,has_package
teacher_id,,,,,,,
55502,3,3,3,3,3,3,3
113638,4,4,4,4,4,4,4
114708,4,4,4,4,4,4,4
132815,5,5,5,5,5,5,5
148092,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...
32167939,2,2,2,2,2,2,2
32168520,3,3,3,3,3,3,3
32169200,1,1,1,1,1,1,1
32169731,1,1,1,1,1,1,1
32171759,1,1,1,1,1,1,1

Pro Course Cleaned JSON generated below when checking if there are duplicated pro courses

Check for any duplicates in the also speaks file\
Check if there are teachers in the 'also_speaks' file but missing in the 'user_course_info' file.

In [28]:
with open('../data_extraction/also_speaks.json', 'r') as file:
    also_speaks_check = json.load(file)

df_also_speaks = pd.DataFrame(also_speaks_check)

No exact duplicates found in the also speaks dataframe.\
Exact duplicates need to be checked because with the user_course_info table, there is a one to many relationship.\
There are teachers who speak multiple other languages so they will have multiple entries in the 'also speaks' table

In [29]:
all_duplicates = df_also_speaks[df_also_speaks.duplicated(keep=False)]
all_duplicates

Empty DataFrame
Columns: [user_id, language]
Index: []

In [30]:
with open('./user_course_info_cleaned.json', 'r') as file:
    user_course_info = json.load(file)

df_user_course_info = pd.DataFrame(user_course_info)

In [31]:
df_num_of_languages = df_also_speaks.groupby('user_id').count().reset_index()

In [32]:
df_num_of_languages[df_num_of_languages['language'] > 0]

        user_id  language
0         55502         3
1        113638         2
2        114708         4
3        132815         2
4        148092         3
...         ...       ...
10289  32167939         3
10290  32168520         1
10291  32169200         1
10292  32169731         1
10293  32171759         4

[10294 rows x 2 columns]

In [33]:
df_merged = pd.merge(df_user_course_info, df_num_of_languages, on='user_id', how='left_anti')

Doing a sample check on these teachers that are in the user_info_cleaned file but not in the also_speaks file, these 176 teachers do in fact only speak one language. Hence they do not appear in the also_speaks file.\
Using the 'right-anti' there are no teachers who appear in the also speaks file but not in the users file.

In [34]:
df_merged

,user_id,nickname,is_tutor,is_pro,origin_country_id,living_country_id,origin_city_id,origin_city_name,living_city_id,living_city_name,timezone,trial_length,has_trial,trial_price,min_price,trial_session_count,has_beginner_course,language
36,595157,Consuelo,1,1,ES,ES,ES00001,Madrid,ES00001,Madrid,Europe/Berlin,2,0,1500,2000,230,0,NaN
44,652005,Scarlet Lorraine,1,1,ZZ,US,ZZ00000,Other,US01071,Sacramento,America/Los_Angeles,2,0,700,1800,782,1,NaN
58,754979,Daniel Colman,0,1,GB,GB,ZZ00000,Other,ZZ00000,Other,Europe/Paris,2,0,500,2200,0,0,NaN
63,795706,Natalia,1,1,RU,RU,ZZ00000,Other,RU00021,Niznij Novgorod,Europe/Moscow,2,0,600,2000,128,1,NaN
89,896917,Faith Valencia,1,0,PH,PH,PH00161,San Fernando,PH00221,Olongapo,Asia/Manila,4,0,750,650,388,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9400,27642857,SAMANTHA KVD,1,0,KE,KE,KE00001,Nairobi,KE00001,Nairobi,Africa/Nairobi,2,0,600,800,4,1,NaN
9986,30333130,Marcus,0,1,US,MX,US01381,Winston-Salem,MX00131,Cancun,America/Cancun,2,0,500,1200,32,0,NaN
9994,30344307,Professeure Gilee,1,0,CA,CA,CA00006,Montreal,CA00006,Montreal,America/Toronto,2,0,2200,4500,1,0,NaN
10284,31409112,Mojomarty,1,0,US,TH,US00951,Philadelphia,TH00000,Other,Asia/Bangkok,2,0,600,2000,0,1,NaN
10393,31823132,Nova L-Zine,1,0,DZ,DZ,DZ00000,Other,DZ00000,Other,Africa/Algiers,2,0,500,700,0,1,NaN

In [35]:
df_merged = pd.merge(df_user_course_info, df_num_of_languages, on='user_id', how='right_anti')

In [36]:
df_merged

Empty DataFrame
Columns: [user_id, nickname, is_tutor, is_pro, origin_country_id, living_country_id, origin_city_id, origin_city_name, living_city_id, living_city_name, timezone, trial_length, has_trial, trial_price, min_price, trial_session_count, has_beginner_course, language]
Index: []

In [37]:
also_speaks_cleaned = df_also_speaks.to_dict(orient='records')

In [38]:
also_speaks_cleaned

[{'user_id': 5467830, 'language': 0},
 {'user_id': 5467830, 'language': 1},
 {'user_id': 5467830, 'language': 2},
 {'user_id': 11401921, 'language': 3},
 {'user_id': 11401921, 'language': 4},
 {'user_id': 11401921, 'language': 5},
 {'user_id': 9627036, 'language': 6},
 {'user_id': 9627036, 'language': 7},
 {'user_id': 5787377, 'language': 8},
 {'user_id': 5787377, 'language': 9},
 {'user_id': 5787377, 'language': 10},
 {'user_id': 5787377, 'language': 1},
 {'user_id': 5787377, 'language': 11},
 {'user_id': 5787377, 'language': 12},
 {'user_id': 5787377, 'language': 0},
 {'user_id': 9934037, 'language': 3},
 {'user_id': 9934037, 'language': 5},
 {'user_id': 7023372, 'language': 0},
 {'user_id': 7023372, 'language': 13},
 {'user_id': 7023372, 'language': 12},
 {'user_id': 7023372, 'language': 14},
 {'user_id': 7023372, 'language': 1},
 {'user_id': 7023372, 'language': 7},
 {'user_id': 7023372, 'language': 5},
 {'user_id': 8226332, 'language': 15},
 {'user_id': 8226332, 'language': 16},
 {'user_id': 8226332, 'language': 7},
 {'user_id': 8226332, 'language': 5},
 {'user_id': 8808840, 'language': 5},
 {'user_id': 11379632, 'language': 5},
 {'user_id': 6381345, 'language': 11},
 {'user_id': 6381345, 'language': 17},
 {'user_id': 6381345, 'language': 18},
 {'user_id': 6381345, 'language': 0},
 {'user_id': 6381345, 'language': 4},
 {'user_id': 6381345, 'language': 19},
 {'user_id': 9781142, 'language': 5},
 {'user_id': 9781142, 'language': 0},
 {'user_id': 8632427, 'language': 5},
 {'user_id': 8632427, 'language': 20},
 {'user_id': 5157554, 'language': 1},
 {'user_id': 5157554, 'language': 12},
 {'user_id': 5157554, 'language': 7},
 {'user_id': 6520785, 'language': 5},
 {'user_id': 6520785, 'language': 21},
 {'user_id': 11364126, 'language': 22},
 {'user_id': 11364126, 'language': 5},
 {'user_id': 6385614, 'language': 23},
 {'user_id': 6385614, 'language': 1},
 {'user_id': 1138564, 'language': 24},
 {'user_id': 1138564, 'language': 25},
 {'user_id': 1138564, 'language': 5},
 {'user_id': 9012382, 'language': 21},
 {'user_id': 9012382, 'language': 5},
 {'user_id': 11920515, 'language': 7},
 {'user_id': 11920515, 'language': 0},
 {'user_id': 11107967, 'language': 26},
 {'user_id': 11240915, 'language': 7},
 {'user_id': 1394274, 'language': 27},
 {'user_id': 1394274, 'language': 15},
 {'user_id': 1394274, 'language': 16},
 {'user_id': 9015804, 'language': 5},
 {'user_id': 5785060, 'language': 23},
 {'user_id': 12948323, 'language': 5},
 {'user_id': 10830189, 'language': 26},
 {'user_id': 10830189, 'language': 5},
 {'user_id': 4203543, 'language': 13},
 {'user_id': 4203543, 'language': 0},
 {'user_id': 10473515, 'language': 3},
 {'user_id': 10473515, 'language': 5},
 {'user_id': 7437294, 'language': 7},
 {'user_id': 7437294, 'language': 11},
 {'user_id': 10354121, 'language': 5},
 {'user_id': 8588012, 'language': 0},
 {'user_id': 8588012, 'language': 5},
 {'user_id': 10599152, 'language': 28},
 {'user_id': 10599152, 'language': 5},
 {'user_id': 13179584, 'language': 5},
 {'user_id': 13543187, 'language': 29},
 {'user_id': 11014379, 'language': 5},
 {'user_id': 6277873, 'language': 11},
 {'user_id': 6277873, 'language': 9},
 {'user_id': 7163738, 'language': 11},
 {'user_id': 4645792, 'language': 11},
 {'user_id': 4645792, 'language': 1},
 {'user_id': 4645792, 'language': 30},
 {'user_id': 4645792, 'language': 13},
 {'user_id': 4645792, 'language': 0},
 {'user_id': 8561488, 'language': 5},
 {'user_id': 6986674, 'language': 11},
 {'user_id': 6986674, 'language': 0},
 {'user_id': 6986674, 'language': 7},
 {'user_id': 12656425, 'language': 5},
 {'user_id': 8377558, 'language': 31},
 {'user_id': 8377558, 'language': 26},
 {'user_id': 22398950, 'language': 20},
 {'user_id': 22398950, 'language': 32},
 {'user_id': 22398950, 'language': 0},
 {'user_id': 8206719, 'language': 5},
 {'user_id': 24267423, 'language': 0},
 {'user_id': 24267423, 'language': 11},
 {'user_id': 24267423, 'language': 30},
 {'user_id': 24267423, 'language': 12},
 {'user_id': 24267423, 'language': 5},
 {'user_id': 26707236, 'language': 1},
 {'user_id': 26707236, 'language': 33},
 {'user_id': 26707236, 'language': 15},
 {'user_id': 26707236, 'language': 23},
 {'user_id': 26707236, 'language': 7},
 {'user_id': 8197005, 'language': 34},
 {'user_id': 8197005, 'language': 1},
 {'user_id': 8197005, 'language': 9},
 {'user_id': 8197005, 'language': 35},
 {'user_id': 8197005, 'language': 5},
 {'user_id': 11345440, 'language': 26},
 {'user_id': 26033613, 'language': 36},
 {'user_id': 26033613, 'language': 0},
 {'user_id': 26033613, 'language': 7},
 {'user_id': 19106723, 'language': 18},
 {'user_id': 19106723, 'language': 11},
 {'user_id': 19106723, 'language': 30},
 {'user_id': 19106723, 'language': 0},
 {'user_id': 28442061, 'language': 15},
 {'user_id': 28442061, 'language': 16},
 {'user_id': 28442061, 'language': 9},
 {'user_id': 7549780, 'language': 1},
 {'user_id': 7549780, 'language': 0},
 {'user_id': 7549780, 'language': 13},
 {'user_id': 7549780, 'language': 12},
 {'user_id': 7549780, 'language': 37},
 {'user_id': 7549780, 'language': 18},
 {'user_id': 7549780, 'language': 19},
 {'user_id': 30014944, 'language': 1},
 {'user_id': 30014944, 'language': 2},
 {'user_id': 30014944, 'language': 11},
 {'user_id': 30014944, 'language': 5},
 {'user_id': 14516927, 'language': 33},
 {'user_id': 14516927, 'language': 11},
 {'user_id': 14516927, 'language': 5},
 {'user_id': 31270228, 'language': 1},
 {'user_id': 31270228, 'language': 11},
 {'user_id': 31270228, 'language': 5},
 {'user_id': 29597016, 'language': 5},
 {'user_id': 30752880, 'language': 38},
 {'user_id': 30752880, 'language': 11},
 {'user_id': 30752880, 'language': 39},
 {'user_id': 30752880, 'language': 1},
 {'user_id': 30752880, 'language': 12},
 {'user_id': 30752880, 'language': 4},
 {'user_id': 17831225, 'language': 0},
 {'user_id': 7495615, 'language': 3},
 {'user_id': 7495615, 'language': 5},
 {'user_id': 7495615, 'language': 0},
 {'user_id': 9934387, 'language': 4},
 {'user_id': 9934387, 'language': 5},
 {'user_id': 8008619, 'language': 5},
 {'user_id': 7900947, 'language': 5},
 {'user_id': 11115905, 'language': 40},
 {'user_id': 11115905, 'language': 26},
 {'user_id': 11115905, 'language': 41},
 {'user_id': 11115905, 'language': 5},
 {'user_id': 5892337, 'language': 0},
 {'user_id': 5892337, 'language': 6},
 {'user_id': 5892337, 'language': 13},
 {'user_id': 5892337, 'language': 30},
 {'user_id': 5892337, 'language': 18},
 {'user_id': 10638714, 'language': 5},
 {'user_id': 13365066, 'language': 7},
 {'user_id': 13365066, 'language': 20},
 {'user_id': 13365066, 'language': 13},
 {'user_id': 13365066, 'language': 0},
 {'user_id': 13365066, 'language': 30},
 {'user_id': 13365066, 'language': 5},
 {'user_id': 11649130, 'language': 5},
 {'user_id': 6997195, 'language': 11},
 {'user_id': 6997195, 'language': 5},
 {'user_id': 10654806, 'language': 42},
 {'user_id': 10654806, 'language': 43},
 {'user_id': 10654806, 'language': 0},
 {'user_id': 10654806, 'language': 5},
 {'user_id': 28084220, 'language': 4},
 {'user_id': 9516444, 'language': 5},
 {'user_id': 18602380, 'language': 5},
 {'user_id': 6283781, 'language': 26},
 {'user_id': 6283781, 'language': 5},
 {'user_id': 8511583, 'language': 30},
 {'user_id': 8511583, 'language': 19},
 {'user_id': 8511583, 'language': 0},
 {'user_id': 11401990, 'language': 5},
 {'user_id': 16974057, 'language': 5},
 {'user_id': 9435621, 'language': 0},
 {'user_id': 9435621, 'language': 5},
 {'user_id': 1424019, 'language': 11},
 {'user_id': 1424019, 'language': 5},
 {'user_id': 8161794, 'language': 7},
 {'user_id': 8161794, 'language': 4},
 {'user_id': 8161794, 'language': 5},
 {'user_id': 6040162, 'language': 11},
 {'user_id': 6040162, 'language': 0},
 {'user_id': 9390336, 'language': 31},
 {'user_id': 9390336, 'language': 5},
 {'user_id': 9390336, 'language': 0},
 {'user_id': 11259849, 'language': 5},
 {'user_id': 19650055, 'language': 5},
 {'user_id': 9173436, 'language': 44},
 {'user_id': 9173436, 'language': 45},
 {'user_id': 9173436, 'language': 0},
 {'user_id': 14055701, 'language': 46},
 {'user_id': 14055701, 'language': 12},
 {'user_id': 14055701, 'language': 18},
 {'user_id': 22403120, 'language': 15},
 {'user_id': 22403120, 'language': 5},
 {'user_id': 10599672, 'language': 26},
 {'user_id': 10446736, 'language': 20},
 {'user_id': 10446736, 'language': 5},
 {'user_id': 10835403, 'language': 5},
 {'user_id': 9185226, 'language': 26},
 {'user_id': 9185226, 'language': 19},
 {'user_id': 4859836, 'language': 47},
 {'user_id': 4859836, 'language': 35},
 {'user_id': 4859836, 'language': 18},
 {'user_id': 4859836, 'language': 48},
 {'user_id': 4859836, 'language': 19},
 {'user_id': 7603855, 'language': 11},
 {'user_id': 7603855, 'language': 14},
 {'user_id': 9464380, 'language': 5},
 {'user_id': 22947542, 'language': 26},
 {'user_id': 22947542, 'language': 20},
 {'user_id': 22947542, 'language': 5},
 {'user_id': 22259321, 'language': 7},
 {'user_id': 22259321, 'language': 49},
 {'user_id': 22259321, 'language': 50},
 {'user_id': 22259321, 'language': 5},
 {'user_id': 22259321, 'language': 28},
 {'user_id': 19887591, 'language': 20},
 {'user_id': 19887591, 'language': 12},
 {'user_id': 31823887, 'language': 3},
 {'user_id': 18412072, 'language': 33},
 {'user_id': 18412072, 'language': 1},
 {'user_id': 18412072, 'language': 11},
 {'user_id': 18412072, 'language': 51},
 {'user_id': 30741613, 'language': 3},
 {'user_id': 30741613, 'language': 21},
 {'user_id': 30741613, 'language': 5},
 {'user_id': 10652686, 'language': 28},
 {'user_id': 10652686, 'language': 5},
 {'user_id': 24998197, 'language': 40},
 {'user_id': 24998197, 'language': 28},
 {'user_id': 24998197, 'language': 20},
 {'user_id': 23794601, 'language': 20},
 {'user_id': 23794601, 'language': 5},
 {'user_id': 10724143, 'language': 52},
 {'user_id': 10724143, 'language': 5},
 {'user_id': 8718689, 'language': 11},
 {'user_id': 19091169, 'language': 5},
 {'user_id': 26591604, 'language': 5},
 {'user_id': 30400672, 'language': 11},
 {'user_id': 30400672, 'language': 5},
 {'user_id': 23877465, 'language': 5},
 {'user_id': 15653827, 'language': 0},
 {'user_id': 15653827, 'language': 25},
 {'user_id': 15653827, 'language': 18},
 {'user_id': 15653827, 'language': 39},
 {'user_id': 15653827, 'language': 49},
 {'user_id': 15653827, 'language': 1},
 {'user_id': 15653827, 'language': 53},
 {'user_id': 7670461, 'language': 54},
 {'user_id': 24798926, 'language': 1},
 {'user_id': 28846434, 'language': 16},
 {'user_id': 28846434, 'language': 5},
 {'user_id': 26060523, 'language': 18},
 {'user_id': 26060523, 'language': 55},
 {'user_id': 3079997, 'language': 0},
 {'user_id': 3079997, 'language': 9},
 {'user_id': 3079997, 'language': 14},
 {'user_id': 3079997, 'language': 56},
 {'user_id': 3079997, 'language': 57},
 {'user_id': 3079997, 'language': 10},
 {'user_id': 3079997, 'language': 58},
 {'user_id': 3079997, 'language': 16},
 {'user_id': 3079997, 'language': 59},
 {'user_id': 3079997, 'language': 18},
 {'user_id': 3079997, 'language': 60},
 {'user_id': 18339018, 'language': 30},
 {'user_id': 18339018, 'language': 4},
 {'user_id': 18339018, 'language': 61},
 {'user_id': 18339018, 'language': 62},
 {'user_id': 18339018, 'language': 63},
 {'user_id': 18339018, 'language': 0},
 {'user_id': 18339018, 'language': 64},
 {'user_id': 30613925, 'language': 0},
 {'user_id': 30613925, 'language': 5},
 {'user_id': 30616446, 'language': 12},
 {'user_id': 30616446, 'language': 5},
 {'user_id': 6195619, 'language': 1},
 {'user_id': 6195619, 'language': 4},
 {'user_id': 6195619, 'language': 0},
 {'user_id': 30860766, 'language': 1},
 {'user_id': 30860766, 'language': 47},
 {'user_id': 30860766, 'language': 35},
 {'user_id': 23409589, 'language': 5},
 {'user_id': 30589958, 'language': 44},
 {'user_id': 30589958, 'language': 65},
 {'user_id': 30589958, 'language': 1},
 {'user_id': 30589958, 'language': 5},
 {'user_id': 30408613, 'language': 11},
 {'user_id': 30408613, 'language': 4},
 {'user_id': 30408613, 'language': 5},
 {'user_id': 10577802, 'language': 0},
 {'user_id': 10577802, 'language': 5},
 {'user_id': 9494384, 'language': 5},
 {'user_id': 11137135, 'language': 66},
 {'user_id': 11137135, 'language': 19},
 {'user_id': 8281200, 'language': 7},
 {'user_id': 8281200, 'language': 11},
 {'user_id': 8281200, 'language': 0},
 {'user_id': 10685078, 'language': 5},
 {'user_id': 9281806, 'language': 3},
 {'user_id': 9281806, 'language': 5},
 {'user_id': 8882739, 'language': 7},
 {'user_id': 8882739, 'language': 4},
 {'user_id': 8882739, 'language': 19},
 {'user_id': 8882739, 'language': 5},
 {'user_id': 10854368, 'language': 0},
 {'user_id': 10854368, 'language': 35},
 {'user_id': 10854368, 'language': 7},
 {'user_id': 10854368, 'language': 30},
 {'user_id': 10854368, 'language': 19},
 {'user_id': 10854368, 'language': 6},
 {'user_id': 11665993, 'language': 21},
 {'user_id': 11665993, 'language': 3},
 {'user_id': 11665993, 'language': 5},
 {'user_id': 5034660, 'language': 18},
 {'user_id': 8878358, 'language': 5},
 {'user_id': 10190710, 'language': 20},
 {'user_id': 10190710, 'language': 5},
 {'user_id': 3456792, 'language': 0},
 {'user_id': 3456792, 'language': 4},
 {'user_id': 3456792, 'language': 13},
 {'user_id': 3456792, 'language': 30},
 {'user_id': 3456792, 'language': 5},
 {'user_id': 28848951, 'language': 7},
 {'user_id': 28848951, 'language': 5},
 {'user_id': 8903161, 'language': 0},
 {'user_id': 8903161, 'language': 13},
 {'user_id': 8903161, 'language': 15},
 {'user_id': 8903161, 'language': 5},
 {'user_id': 7522813, 'language': 0},
 {'user_id': 7522813, 'language': 5},
 {'user_id': 11364173, 'language': 5},
 {'user_id': 5582725, 'language': 60},
 {'user_id': 5582725, 'language': 15},
 {'user_id': 5582725, 'language': 11},
 {'user_id': 10003882, 'language': 21},
 {'user_id': 10003882, 'language': 5},
 {'user_id': 10009812, 'language': 5},
 {'user_id': 9165916, 'language': 52},
 {'user_id': 9165916, 'language': 5},
 {'user_id': 9505145, 'language': 5},
 {'user_id': 9431954, 'language': 1},
 {'user_id': 7968497, 'language': 5},
 {'user_id': 7968497, 'language': 0},
 {'user_id': 9281659, 'language': 5},
 {'user_id': 10192337, 'language': 31},
 {'user_id': 10192337, 'language': 26},
 {'user_id': 10192337, 'language': 42},
 {'user_id': 10192337, 'language': 19},
 {'user_id': 10192337, 'language': 4},
 {'user_id': 10192337, 'language': 5},
 {'user_id': 8854442, 'language': 47},
 {'user_id': 8854442, 'language': 11},
 {'user_id': 8854442, 'language': 5},
 {'user_id': 10084039, 'language': 40},
 {'user_id': 10084039, 'language': 26},
 {'user_id': 10084039, 'language': 5},
 {'user_id': 12584477, 'language': 30},
 {'user_id': 12584477, 'language': 5},
 {'user_id': 12933058, 'language': 5},
 {'user_id': 5737246, 'language': 0},
 {'user_id': 5737246, 'language': 35},
 {'user_id': 5737246, 'language': 12},
 {'user_id': 5737246, 'language': 61},
 {'user_id': 5737246, 'language': 13},
 {'user_id': 5737246, 'language': 18},
 {'user_id': 5273058, 'language': 10},
 {'user_id': 5273058, 'language': 11},
 {'user_id': 13544450, 'language': 5},
 {'user_id': 3456386, 'language': 19},
 {'user_id': 3456386, 'language': 4},
 {'user_id': 3456386, 'language': 0},
 {'user_id': 14684199, 'language': 4},
 {'user_id': 14684199, 'language': 19},
 {'user_id': 14684199, 'language': 5},
 {'user_id': 14684199, 'language': 0},
 {'user_id': 6395849, 'language': 20},
 {'user_id': 6395849, 'language': 0},
 {'user_id': 6395849, 'language': 11},
 {'user_id': 6395849, 'language': 12},
 {'user_id': 6395849, 'language': 7},
 {'user_id': 6395849, 'language': 5},
 {'user_id': 6395849, 'language': 13},
 {'user_id': 6395849, 'language': 18},
 {'user_id': 7466295, 'language': 15},
 {'user_id': 7466295, 'language': 33},
 {'user_id': 7167168, 'language': 5},
 {'user_id': 12388851, 'language': 5},
 {'user_id': 12442247, 'language': 40},
 {'user_id': 12442247, 'language': 28},
 {'user_id': 12442247, 'language': 26},
 {'user_id': 12442247, 'language': 41},
 {'user_id': 12442247, 'language': 20},
 {'user_id': 5360261, 'language': 5},
 {'user_id': 14604918, 'language': 3},
 {'user_id': 14604918, 'language': 1},
 {'user_id': 8896541, 'language': 1},
 {'user_id': 8896541, 'language': 12},
 {'user_id': 25512643, 'language': 1},
 {'user_id': 25512643, 'language': 7},
 {'user_id': 25512643, 'language': 67},
 {'user_id': 25512643, 'language': 16},
 {'user_id': 25512643, 'language': 68},
 {'user_id': 25512643, 'language': 9},
 {'user_id': 25512643, 'language': 5},
 {'user_id': 7175050, 'language': 5},
 {'user_id': 10013855, 'language': 11},
 {'user_id': 10013855, 'language': 5},
 {'user_id': 5474528, 'language': 11},
 {'user_id': 5474528, 'language': 0},
 {'user_id': 6192375, 'language': 12},
 {'user_id': 8880537, 'language': 5},
 {'user_id': 23005594, 'language': 52},
 {'user_id': 23005594, 'language': 26},
 {'user_id': 23005594, 'language': 28},
 {'user_id': 23005594, 'language': 41},
 {'user_id': 23005594, 'language': 20},
 {'user_id': 23005594, 'language': 0},
 {'user_id': 23005594, 'language': 5},
 {'user_id': 30198420, 'language': 2},
 {'user_id': 30198420, 'language': 35},
 {'user_id': 30198420, 'language': 5},
 {'user_id': 10579116, 'language': 41},
 {'user_id': 10579116, 'language': 26},
 {'user_id': 10579116, 'language': 5},
 {'user_id': 7827093, 'language': 0},
 {'user_id': 26031409, 'language': 5},
 {'user_id': 31403292, 'language': 7},
 {'user_id': 3941839, 'language': 0},
 {'user_id': 3941839, 'language': 61},
 {'user_id': 3941839, 'language': 12},
 {'user_id': 4321538, 'language': 11},
 {'user_id': 12562755, 'language': 31},
 {'user_id': 12562755, 'language': 9},
 {'user_id': 12562755, 'language': 11},
 {'user_id': 12562755, 'language': 5},
 {'user_id': 29088671, 'language': 9},
 {'user_id': 29088671, 'language': 11},
 {'user_id': 29088671, 'language': 5},
 {'user_id': 29088671, 'language': 0},
 {'user_id': 15559503, 'language': 5},
 {'user_id': 23419428, 'language': 15},
 {'user_id': 23419428, 'language': 16},
 {'user_id': 23419428, 'language': 12},
 {'user_id': 23007961, 'language': 5},
 {'user_id': 26035360, 'language': 11},
 {'user_id': 26035360, 'language': 12},
 {'user_id': 26035360, 'language': 5},
 {'user_id': 30200169, 'language': 1},
 {'user_id': 28854982, 'language': 49},
 {'user_id': 28854982, 'language': 11},
 {'user_id': 28854982, 'language': 5},
 {'user_id': 29822522, 'language': 2},
 {'user_id': 29822522, 'language': 35},
 {'user_id': 29822522, 'language': 5},
 {'user_id': 13430486, 'language': 5},
 {'user_id': 28840128, 'language': 13},
 {'user_id': 28840128, 'language': 0},
 {'user_id': 28840128, 'language': 4},
 {'user_id': 28840128, 'language': 18},
 {'user_id': 28840128, 'language': 12},
 {'user_id': 28840128, 'language': 7},
 {'user_id': 28840128, 'language': 11},
 {'user_id': 28840128, 'language': 14},
 {'user_id': 14604365, 'language': 15},
 {'user_id': 14604365, 'language': 33},
 {'user_id': 29822483, 'language': 1},
 {'user_id': 29822483, 'language': 2},
 {'user_id': 31615258, 'language': 5},
 {'user_id': 9973436, 'language': 5},
 {'user_id': 24932566, 'language': 41},
 {'user_id': 24932566, 'language': 26},
 {'user_id': 24932566, 'language': 19},
 {'user_id': 24932566, 'language': 61},
 {'user_id': 9293613, 'language': 69},
 {'user_id': 9293613, 'language': 5},
 {'user_id': 19125102, 'language': 35},
 {'user_id': 19125102, 'language': 5},
 {'user_id': 29822064, 'language': 1},
 {'user_id': 29822064, 'language': 12},
 {'user_id': 5960994, 'language': 0},
 {'user_id': 5960994, 'language': 11},
 {'user_id': 31178086, 'language': 13},
 {'user_id': 31178086, 'language': 0},
 {'user_id': 31178086, 'language': 11},
 {'user_id': 26037221, 'language': 5},
 {'user_id': 23006632, 'language': 15},
 {'user_id': 23006632, 'language': 16},
 {'user_id': 23006632, 'language': 33},
 {'user_id': 23006632, 'language': 5},
 {'user_id': 23609642, 'language': 13},
 {'user_id': 23609642, 'language': 0},
 {'user_id': 23609642, 'language': 11},
 {'user_id': 23609642, 'language': 12},

In [112]:
with open('./also_speaks_cleaned.json', 'w') as file:
        json.dump(also_speaks_cleaned, file, indent=4)

Check that Every Pro Course is tagged to a teacher.\
There are teachers with multiple pro courses.

In [39]:
with open('./user_course_info_cleaned.json', 'r') as file:
    user_course_info = json.load(file)

df_user_course_info = pd.DataFrame(user_course_info)

In [40]:
with open('../data_extraction/pro_course.json', 'r') as file:
    pro_course_check = json.load(file)

df_pro_course_check = pd.DataFrame(pro_course_check)

In [41]:
df_pro_course_check

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
0,146280,5467830,chinese,【For new student】 Customized Lesson (A1~C2） /...,6000,260,1455,1
1,146282,5467830,chinese,【Special discount for long-term students who h...,5800,61,980,1
2,148875,5467830,chinese,(No Video & No Audio Call) Essay Correction wi...,500,14,32,0
3,186046,5467830,english,【For new student 新生课】 个人定制课程 / カスタマイズレッスン,6000,62,196,1
4,186049,5467830,english,【无需见面的作文修改】 (No Video & No Audio Call) / Ess...,500,6,8,0
...,...,...,...,...,...,...,...,...
40066,249718,23372570,korean,Korean Structure Master,5000,2,11,1
40067,249721,23372570,korean,Intensive Korean for Upper level,5000,0,0,1
40068,139499,8296973,korean,Beginner/Intermediate,5000,45,912,1
40069,139502,8296973,korean,"Academic writing (한국어 전공자, 유학생)",7000,2,17,0
40070,139510,8296973,korean,Advanced level (with authentic materials),5000,12,98,1

The following code block shows that every course has a teacher mapped to it.

In [42]:
df_merged = pd.merge(df_user_course_info, df_pro_course_check, left_on='user_id', right_on='teacher_id', how='right_anti')
df_merged

Empty DataFrame
Columns: [user_id, nickname, is_tutor, is_pro, origin_country_id, living_country_id, origin_city_id, origin_city_name, living_city_id, living_city_name, timezone, trial_length, has_trial, trial_price, min_price, trial_session_count, has_beginner_course, id, teacher_id, language, title, session_price, student_count, session_count, has_package]
Index: []

[0 rows x 25 columns]

The following code block shows that the number of teachers in the pro course table matches the user_course_info table as there are 10470 unique teachers

In [43]:
df_pro_course_check.groupby('teacher_id').count()

,id,language,title,session_price,student_count,session_count,has_package
teacher_id,,,,,,,
55502,3,3,3,3,3,3,3
113638,4,4,4,4,4,4,4
114708,4,4,4,4,4,4,4
132815,5,5,5,5,5,5,5
148092,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...
32167939,2,2,2,2,2,2,2
32168520,3,3,3,3,3,3,3
32169200,1,1,1,1,1,1,1
32169731,1,1,1,1,1,1,1
32171759,1,1,1,1,1,1,1

In [44]:
df_pro_course_check['teacher_id'].nunique()

10470

There are duplicate pro course id which should not be the case.\
If there id, teacher_id and the language are the same, the later one should be taken meaning sort by id and session count.\
The higher session count will be taken

In [45]:
df_pro_course_check['id'].nunique()

39035

In [46]:
df_pro_course_check_id = df_pro_course_check.groupby('id').count().reset_index()

In [47]:
df_pro_course_check_id

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
0,375,1,1,1,1,1,1,1
1,555,1,1,1,1,1,1,1
2,946,2,2,2,2,2,2,2
3,3190,1,1,1,1,1,1,1
4,4042,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...
39030,290784,1,1,1,1,1,1,1
39031,290785,1,1,1,1,1,1,1
39032,290788,1,1,1,1,1,1,1
39033,290792,1,1,1,1,1,1,1
39034,290796,1,1,1,1,1,1,1

In [48]:
df_pro_course_check[df_pro_course_check['id'] == 946]

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
11617,946,502096,serbian,Serbian for all levels! 100% target language l...,2300,80,1112,1
35999,946,502096,serbian,Serbian for all levels! 100% target language l...,2300,80,1113,1

There are 40071 rows in the pro course table but only 39035 unique ids.

In [49]:
all_duplicates = df_pro_course_check[df_pro_course_check.duplicated(subset=['id', 'teacher_id', 'language'], keep=False)]
all_duplicates

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
0,146280,5467830,chinese,【For new student】 Customized Lesson (A1~C2） /...,6000,260,1455,1
41,101184,7023372,russian,🇷🇺 General Course - Russian for Beginners (A0-A2),2500,96,575,1
43,101662,7023372,english,🇺🇲🇨🇦🇬🇧 General English Course (Including Engli...,3000,107,1176,1
47,258619,7023372,russian,🇷🇺 NEW! Russian for Kids and Teenagers - Русск...,2500,4,172,1
384,269540,28084220,english,Free-Form Conversation in English (For adults),690,38,203,1
...,...,...,...,...,...,...,...,...
39814,221255,5728578,korean,All Skills in Korean,4500,81,2345,1
39815,247686,5728578,korean,TOPIK II Preparation (NEW! 📚📖💯),4700,4,52,1
39847,251333,23907480,korean,Korean for Beginner to Intermediate,3000,41,848,1
39858,253792,24885652,korean,Exciting Beginner Korean Lesson! [Customized f...,4300,17,222,1
39867,166826,9484347,english,English Conversation Practice,3000,52,152,1

In [50]:
pro_count_dup_count = all_duplicates.groupby('id').count().reset_index()
pro_count_dup_count

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
0,946,2,2,2,2,2,2,2
1,11943,2,2,2,2,2,2,2
2,13127,2,2,2,2,2,2,2
3,13362,2,2,2,2,2,2,2
4,14210,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...
1022,289067,2,2,2,2,2,2,2
1023,289068,2,2,2,2,2,2,2
1024,289069,2,2,2,2,2,2,2
1025,289287,2,2,2,2,2,2,2
1026,290415,2,2,2,2,2,2,2

In [51]:
pro_count_dup_count[pro_count_dup_count['teacher_id'] == 2]

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
0,946,2,2,2,2,2,2,2
1,11943,2,2,2,2,2,2,2
2,13127,2,2,2,2,2,2,2
3,13362,2,2,2,2,2,2,2
4,14210,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...
1022,289067,2,2,2,2,2,2,2
1023,289068,2,2,2,2,2,2,2
1024,289069,2,2,2,2,2,2,2
1025,289287,2,2,2,2,2,2,2
1026,290415,2,2,2,2,2,2,2

In [52]:
df_sorted = all_duplicates.sort_values(by=['teacher_id', 'id', 'session_count'], ascending=[True, True, True])
df_sorted

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
4869,11943,222305,portuguese,Português,1499,437,2337,1
19299,11943,222305,portuguese,Português,1499,439,2341,1
4871,21847,222305,german,German,1499,582,3569,1
19300,21847,222305,german,German,1499,582,3571,1
4875,40640,222305,german,Deutsch,1499,423,1966,1
...,...,...,...,...,...,...,...,...
20448,286810,31265601,italian,(Matthew) 02-IT - Lezione personalizzata di it...,2500,10,94,1
918,288579,31823132,english,english basics: conversation practice,700,2,4,1
18422,288579,31823132,english,english basics,700,2,4,1
919,288693,31823132,french,français basique: conversation,700,11,24,1
18423,288693,31823132,french,conversation en français,700,12,27,1

In [53]:
df_pro_course_sorted = df_pro_course_check.sort_values(by=['id', 'teacher_id', 'session_count'], ascending=[True, True, True])
df_pro_course_no_dup = df_pro_course_sorted.drop_duplicates(subset=['id', 'teacher_id', 'language'], keep='last')
df_pro_course_no_dup

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
22570,375,436016,english,English courses新概念英语（1）,1400,15,106,0
22571,555,436016,chinese,Young Learners' Chinese,1600,5,37,1
35999,946,502096,serbian,Serbian for all levels! 100% target language l...,2300,80,1113,1
22572,3190,436016,chinese,One-on-One Customized Chinese lesson,1500,73,1391,1
14692,4042,463477,english,One-on-One tutoring: English,3200,95,1504,1
...,...,...,...,...,...,...,...,...
18747,290784,31481128,french,🗣️ Natural French Conversation: Speak easily !,700,0,0,1
18455,290785,8513543,french,Leçon d'essai,800,0,0,0
38856,290788,29325526,korean,For Long-term Students,1300,0,0,1
29884,290792,6417813,spanish,DELE exam preparation / Preparación para el ex...,2700,0,0,1
21580,290796,31472940,french,French for Kids and Beginners,4000,0,0,1

In [54]:
df_pro_course_no_dup[df_pro_course_no_dup['id'] == 946]

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
35999,946,502096,serbian,Serbian for all levels! 100% target language l...,2300,80,1113,1

In [55]:
pro_course_cleaned = df_pro_course_no_dup.to_dict(orient='records')

In [56]:
pro_course_cleaned

[{'id': 375,
  'teacher_id': 436016,
  'language': 'english',
  'title': 'English courses新概念英语（1）',
  'session_price': 1400,
  'student_count': 15,
  'session_count': 106,
  'has_package': 0},
 {'id': 555,
  'teacher_id': 436016,
  'language': 'chinese',
  'title': "Young Learners' Chinese",
  'session_price': 1600,
  'student_count': 5,
  'session_count': 37,
  'has_package': 1},
 {'id': 946,
  'teacher_id': 502096,
  'language': 'serbian',
  'title': 'Serbian for all levels! 100% target language lessons!',
  'session_price': 2300,
  'student_count': 80,
  'session_count': 1113,
  'has_package': 1},
 {'id': 3190,
  'teacher_id': 436016,
  'language': 'chinese',
  'title': 'One-on-One Customized Chinese lesson',
  'session_price': 1500,
  'student_count': 73,
  'session_count': 1391,
  'has_package': 1},
 {'id': 4042,
  'teacher_id': 463477,
  'language': 'english',
  'title': 'One-on-One tutoring: English',
  'session_price': 3200,
  'student_count': 95,
  'session_count': 1504,
  'has_package': 1},
 {'id': 5620,
  'teacher_id': 499227,
  'language': 'bulgarian',
  'title': 'Bulgarian (levels A1, A2, B1, B2)   / A 10% discount for a 10-lesson package :)',
  'session_price': 3400,
  'student_count': 167,
  'session_count': 3872,
  'has_package': 1},
 {'id': 5779,
  'teacher_id': 502096,
  'language': 'english',
  'title': 'One-on-One tutoring: English',
  'session_price': 2300,
  'student_count': 84,
  'session_count': 876,
  'has_package': 1},
 {'id': 6470,
  'teacher_id': 517538,
  'language': 'spanish',
  'title': "One to one tutoring: Let's learn Spanish together! - Spanish lessons for all levels",
  'session_price': 2200,
  'student_count': 686,
  'session_count': 7136,
  'has_package': 1},
 {'id': 7313,
  'teacher_id': 535501,
  'language': 'spanish',
  'title': 'Spanish lessons One-on-One',
  'session_price': 3100,
  'student_count': 87,
  'session_count': 1159,
  'has_package': 1},
 {'id': 8425,
  'teacher_id': 538395,
  'language': 'japanese',
  'title': 'COMMUNICATIVE JAPANESE（Conversation practice)',
  'session_price': 1700,
  'student_count': 215,
  'session_count': 3205,
  'has_package': 1},
 {'id': 8775,
  'teacher_id': 259649,
  'language': 'chinese',
  'title': 'Elementary Chinese Course',
  'session_price': 1590,
  'student_count': 461,
  'session_count': 4805,
  'has_package': 1},
 {'id': 9022,
  'teacher_id': 516278,
  'language': 'german',
  'title': '** GERMAN PROFICIENCY ★ 50 X 90 min ► All levels ► $ 34.38 per hour',
  'session_price': 6090,
  'student_count': 84,
  'session_count': 723,
  'has_package': 1},
 {'id': 9024,
  'teacher_id': 516278,
  'language': 'german',
  'title': '★ NEXT LEVEL GERMAN ★ 40 X 90 min ► All levels ► $37.48/h',
  'session_price': 6090,
  'student_count': 70,
  'session_count': 278,
  'has_package': 1},
 {'id': 9663,
  'teacher_id': 499227,
  'language': 'russian',
  'title': 'Russian (levels A1, A2, B1, B2) / A 10% discount for a 10-lesson package :)',
  'session_price': 3400,
  'student_count': 32,
  'session_count': 847,
  'has_package': 1},
 {'id': 9835,
  'teacher_id': 595157,
  'language': 'spanish',
  'title': 'Clase profesional - todos los niveles.',
  'session_price': 2000,
  'student_count': 374,
  'session_count': 5335,
  'has_package': 1},
 {'id': 9878,
  'teacher_id': 436016,
  'language': 'chinese',
  'title': 'Beginner level Chinese',
  'session_price': 1500,
  'student_count': 37,
  'session_count': 114,
  'has_package': 1},
 {'id': 9879,
  'teacher_id': 436016,
  'language': 'chinese',
  'title': 'Intermediate—advanced level Chinese Courses',
  'session_price': 1500,
  'student_count': 30,
  'session_count': 232,
  'has_package': 1},
 {'id': 10048,
  'teacher_id': 596847,
  'language': 'english',
  'title': 'English language instruction',
  'session_price': 2600,
  'student_count': 147,
  'session_count': 2881,
  'has_package': 1},
 {'id': 10083,
  'teacher_id': 436016,
  'language': 'chinese',
  'title': '商务汉语BusineseChinese',
  'session_price': 1500,
  'student_count': 11,
  'session_count': 59,
  'has_package': 1},
 {'id': 10102,
  'teacher_id': 600986,
  'language': 'japanese',
  'title': 'One-on-One tutoring: japanese',
  'session_price': 1700,
  'student_count': 745,
  'session_count': 5650,
  'has_package': 1},
 {'id': 10161,
  'teacher_id': 516278,
  'language': 'german',
  'title': '★ GERMAN IMMERSION ★ 30 X 90 min ► All levels ► $40.87 per hour ✔',
  'session_price': 6090,
  'student_count': 46,
  'session_count': 371,
  'has_package': 1},
 {'id': 10779,
  'teacher_id': 483024,
  'language': 'english',
  'title': 'English Pronunciation & Intonation',
  'session_price': 6500,
  'student_count': 49,
  'session_count': 90,
  'has_package': 1},
 {'id': 10780,
  'teacher_id': 483024,
  'language': 'english',
  'title': 'CV Review & Job Interview Skills in English',
  'session_price': 7500,
  'student_count': 56,
  'session_count': 81,
  'has_package': 0},
 {'id': 10796,
  'teacher_id': 113638,
  'language': 'chinese',
  'title': 'One-on-one tutoring: practical chinese',
  'session_price': 3500,
  'student_count': 249,
  'session_count': 3435,
  'has_package': 1},
 {'id': 11012,
  'teacher_id': 600465,
  'language': 'turkish',
  'title': 'Turkish Lessons (For all levels)',
  'session_price': 3700,
  'student_count': 211,
  'session_count': 6016,
  'has_package': 1},
 {'id': 11084,
  'teacher_id': 596847,
  'language': 'english',
  'title': 'IELTS preparation',
  'session_price': 2700,
  'student_count': 214,
  'session_count': 2529,
  'has_package': 1},
 {'id': 11135,
  'teacher_id': 499227,
  'language': 'english',
  'title': 'English (levels A1-B2)',
  'session_price': 3400,
  'student_count': 22,
  'session_count': 254,
  'has_package': 1},
 {'id': 11164,
  'teacher_id': 652005,
  'language': 'english',
  'title': 'General Business English ( Basic/ Intermediate/Advanced) - Integrated with Audio OR Business English for Specific Profession/ Fields /Work Skills',
  'session_price': 2000,
  'student_count': 505,
  'session_count': 3383,
  'has_package': 1},
 {'id': 11165,
  'teacher_id': 652005,
  'language': 'english',
  'title': 'Talk your Head off (Conversational English)',
  'session_price': 2000,
  'student_count': 666,
  'session_count': 7715,
  'has_package': 1},
 {'id': 11184,
  'teacher_id': 259649,
  'language': 'chinese',
  'title': 'Spoken Chinese',
  'session_price': 1590,
  'student_count': 156,
  'session_count': 426,
  'has_package': 1},
 {'id': 11204,
  'teacher_id': 652005,
  'language': 'english',
  'title': 'Personalized Instruction (Speaking/Reading/Listening/Grammar) -Integrated with Audio  ; Basic/ Intermediate/Advanced Grammar Lessons',
  'session_price': 2000,
  'student_count': 718,
  'session_count': 9850,
  'has_package': 1},
 {'id': 11263,
  'teacher_id': 652005,
  'language': 'english',
  'title': 'English for Travelers',
  'session_price': 1800,
  'student_count': 29,
  'session_count': 104,
  'has_package': 0},
 {'id': 11266,
  'teacher_id': 652005,
  'language': 'english',
  'title': 'Speaking Preparation for TOEFL, IELTS, PET, FCE,CAE or CELPIP',
  'session_price': 2000,
  'student_count': 356,
  'session_count': 2467,
  'has_package': 1},
 {'id': 11444,
  'teacher_id': 658229,
  'language': 'english',
  'title': 'British English',
  'session_price': 3500,
  'student_count': 507,
  'session_count': 7256,
  'has_package': 1},
 {'id': 11746,
  'teacher_id': 55502,
  'language': 'chinese',
  'title': 'Intermediate - Advanced Level Learner B1-C1 / HSK3-HSK5',
  'session_price': 2100,
  'student_count': 91,
  'session_count': 726,
  'has_package': 1},
 {'id': 11943,
  'teacher_id': 222305,
  'language': 'portuguese',
  'title': 'Português',
  'session_price': 1499,
  'student_count': 439,
  'session_count': 2341,
  'has_package': 1},
 {'id': 12030,
  'teacher_id': 658229,
  'language': 'english',
  'title': 'IELTS preparation',
  'session_price': 3879,
  'student_count': 310,
  'session_count': 2448,
  'has_package': 1},
 {'id': 12032,
  'teacher_id': 658229,
  'language': 'english',
  'title': 'Interview skills',
  'session_price': 4900,
  'student_count': 113,
  'session_count': 228,
  'has_package': 0},
 {'id': 13038,
  'teacher_id': 745006,
  'language': 'english',
  'title': 'Business English 商务英语',
  'session_price': 5500,
  'student_count': 229,
  'session_count': 1236,
  'has_package': 1},
 {'id': 13127,
  'teacher_id': 745006,
  'language': 'english',
  'title': 'Interview Preparation or Test Preparation (TOEFL/ IELTS / GRE/ PET/ TOEIC/ SSAT/ Junior TOEFL and more)',
  'session_price': 5200,
  'student_count': 129,
  'session_count': 769,
  'has_package': 1},
 {'id': 13175,
  'teacher_id': 754436,
  'language': 'english',
  'title': 'Basic to Advanced Tutoring in English',
  'session_price': 2800,
  'student_count': 93,
  'session_count': 1687,
  'has_package': 1},
 {'id': 13193,
  'teacher_id': 754979,
  'language': 'english',
  'title': 'Unique, planned, structured English lessons.',
  'session_price': 2600,
  'student_count': 160,
  'session_count': 3622,
  'has_package': 1},
 {'id': 13267,
  'teacher_id': 755192,
  'language': 'english',
  'title': 'IELTS Preparation',
  'session_price': 1000,
  'student_count': 81,
  'session_count': 298,
  'has_package': 1},
 {'id': 13335,
  'teacher_id': 502096,
  'language': 'italian',
  'title': 'Italian for all levels! 100% target language lessons!',
  'session_price': 2300,
  'student_count': 75,
  'session_count': 664,
  'has_package': 1},
 {'id': 13362,
  'teacher_id': 745006,
  'language': 'english',
  'title': 'English Pronunciation and Intonation Training',
  'session_price': 5000,
  'student_count': 98,
  'session_count': 700,
  'has_package': 1},
 {'id': 13504,
  'teacher_id': 687031,
  'language': 'english',
  'title': 'CEFR Upgrade (A1-C2) (8 levels) - Oxford English File - British and American Versions Available.. (I only teach adults and teenagers 13+)',
  'session_price': 3500,
  'student_count': 636,
  'session_count': 21219,
  'has_package': 1},
 {'id': 13600,
  'teacher_id': 755192,
  'language': 'english',
  'title': 'English letter writing',
  'session_price': 1000,
  'student_count': 13,
  'session_count': 61,
  'has_package': 1},
 {'id': 13679,
  'teacher_id': 754436,
  'language': 'english',
  'title': 'Speaking Fluency',
  'session_price': 2800,
  'student_count': 177,
  'session_count': 3287,
  'has_package': 1},
 {'id': 14210,
  'teacher_id': 707465,
  'language': 'spanish',
  'title': '¡Hablemos Español!',
  'session_price': 3600,
  'student_count': 685,
  'session_count': 8853,
  'has_package': 1},
 {'id': 14348,
  'teacher_id': 745006,
  'language': 'english',
  'title': 'One-on-One Tutoring: English 一对一美式英文课程',
  'session_price': 4800,
  'student_count': 295,
  'session_count': 3437,
  'has_package': 1},
 {'id': 14653,
  'teacher_id': 811320,
  'language': 'spanish',
  'title': 'Personal Tutoring',
  'session_price': 3100,
  'student_count': 393,
  'session_count': 6356,
  'has_package': 1},
 {'id': 14654,
  'teacher_id': 745006,
  'language': 'chinese',
  'title': 'CSP & ESP (Chinese/ English for Specific Purposes) 专用汉语／专用英语  & Chinese/English Translation Service 翻译服务',
  'session_price': 7500,
  'student_count': 25,
  'session_count': 131,
  'has_package': 1},
 {'id': 14683,
  'teacher_id': 815733,
  'language': 'korean',
  'title': 'Korean Conversation Practice – Speak Mostly in Korean (65% or more!) (최대한 한국어로 말해보는 수업입니다!)',
  'session_price': 3000,
  'student_count': 74,
  'session_count': 538,
  'has_package': 1},
 {'id': 14706,
  'teacher_id': 738970,
  'language': 'japanese',
  'title': 'Japanese Lesson',
  'session_price': 3200,
  'student_count': 186,
  'session_count': 1861,
  'has_package': 1},
 {'id': 14741,
  'teacher_id': 818089,
  'language': 'english',
  'title': 'Hindi - Elementary Hindi Proficiency Course -  A 1',
  'session_price': 2600,
  'student_count': 108,
  'session_count': 894,
  'has_package': 1},
 {'id': 14844,
  'teacher_id': 818089,
  'language': 'english',
  'title': 'Hindi - Lower Intermediate Hindi Proficiency course - A 2',
  'session_price': 2600,
  'student_count': 46,
  'session_count': 716,
  'has_package': 1},
 {'id': 14845,
  'teacher_id': 818089,
  'language': 'english',
  'title': 'Hindi - Upper Intermediate Hindi Proficiency  Course - A 3',
  'session_price': 2600,
  'student_count': 13,
  'session_count': 307,
  'has_package': 1},
 {'id': 15199,
  'teacher_id': 835769,
  'language': 'chinese',
  'title': 'Chinese Made Easier and Supplementary Reading (实用速成汉语及补充阅读)',
  'session_price': 3000,
  'student_count': 96,
  'session_count': 1381,
  'has_package': 1},
 {'id': 15639,
  'teacher_id': 774968,
  'language': 'english',
  'title': 'Accent Reduction  (Pronunciation)',
  'session_price': 2000,
  'student_count': 354,
  'session_count': 3160,
  'has_package': 1},
 {'id': 15640,
  'teacher_id': 774968,
  'language': 'english',
  'title': 'English Conversation',
  'session_price': 1800,
  'student_count': 796,
  'session_count': 6099,
  'has_package': 1},
 {'id': 15641,
  'teacher_id': 774968,
  'language': 'english',
  'title': 'Writing/Academic Writing Course',
  'session_price': 2000,
  'student_count': 90,
  'session_count': 736,
  'has_package': 1},
 {'id': 15702,
  'teacher_id': 774968,
  'language': 'english',
  'title': 'Business English - ALL Industries - ALL Business related topics',
  'session_price': 1800,
  'student_count': 192,
  'session_count': 1211,
  'has_package': 1},
 {'id': 15797,
  'teacher_id': 836912,
  'language': 'english',
  'title': 'Conversational English',
  'session_price': 2200,
  'student_count': 104,
  'session_count': 1844,
  'has_package': 1},
 {'id': 16950,
  'teacher_id': 904516,
  'language': 'english',
  'title': 'Pronunciation, Practising Conversation, Vocabulary',
  'session_price': 2400,
  'student_count': 300,
  'session_count': 1887,
  'has_package': 0},
 {'id': 16972,
  'teacher_id': 745006,
  'language': 'chinese',
  'title': 'One-on-One Tutoring: Chinese & HSK Preparation',
  'session_price': 5500,
  'student_count': 110,
  'session_count': 1428,
  'has_package': 1},
 {'id': 17071,
  'teacher_id': 835769,
  'language': 'chinese',
  'title': '一对一辅导: 中文(普通话)Intermediate/Advanced level',
  'session_price': 3000,
  'student_count': 119,
  'session_count': 887,
  'has_package': 1},
 {'id': 17115,
  'teacher_id': 889879,
  'language': 'spanish',
  'title': 'Spanish pronunciation lesson (Accent reduction)',
  'session_price': 2000,
  'student_count': 54,
  'session_count': 404,
  'has_package': 1},
 {'id': 17216,
  'teacher_id': 916033,
  'language': 'japanese',
  'title': '📕 Structured lessons with online textbooks',
  'session_price': 5800,
  'student_count': 313,
  'session_count': 1594,
  'has_package': 1},
 {'id': 17388,
  'teacher_id': 904516,
  'language': 'english',
  'title': 'Test preparation for IELTS',
  'session_price': 2600,
  'student_count': 101,
  'session_count': 830,
  'has_package': 0},
 {'id': 17390,
  'teacher_id': 663702,
  'language': 'french',
  'title': '🗣🤩 START SPEAKING FRENCH - Structured lessons - French for beginners',
  'session_price': 4200,
  'student_count': 210,
  'session_count': 2556,
  'has_package': 1},
 {'id': 17676,
  'teacher_id': 878142,
  'language': 'arabic',
  'title': 'One-on-One tutoring: Arabic',
  'session_price': 1800,
  'student_count': 41,
  'session_count': 388,
  'has_package': 1},
 {'id': 17826,
  'teacher_id': 755192,
  'language': 'english',
  'title': 'Job Interview Preparation',
  'session_price': 1000,
  'student_count': 42,
  'session_count': 98,
  'has_package': 1},
 {'id': 18087,
  'teacher_id': 835769,
  'language': 'chinese',
  'title': 'Pinyin（For totally beginners）',
  'session_price': 3000,
  'student_count': 35,
  'session_count': 205,
  'has_package': 1},
 {'id': 18179,
  'teacher_id': 949187,
  'language': 'french',
  'title': 'INTENSIVE COURSE FOR ANY LEVEL    A0 - A1 - A2 - B1 - B2 - C1',
  'session_price': 1600,
  'student_count': 419,
  'session_count': 1879,
  'has_package': 1},
 {'id': 18298,
  'teacher_id': 953599,
  'language': 'english',
  'title': 'Kids and Teens English Class👧🏻👦🏻 (Improve the speaking, reading, writing and listening)',
  'session_price': 2000,
  'student_count': 36,
  'session_count': 571,
  'has_package': 1},
 {'id': 18316,
  'teacher_id': 949187,
  'language': 'french',
  'title': 'GRAMMAR - VOCABULARY WITH EXCERCICES A0 .....C1',
  'session_price': 1400,
  'student_count': 149,
  'session_count': 603,
  'has_package': 1},
 {'id': 18328,
  'teacher_id': 949187,
  'language': 'french',
  'title': 'READING - WRITING',
  'session_price': 1400,
  'student_count': 32,
  'session_count': 101,
  'has_package': 1},
 {'id': 18506,
  'teacher_id': 113638,
  'language': 'chinese',
  'title': 'Informal Tutoring',
  'session_price': 3000,
  'student_count': 89,
  'session_count': 937,
  'has_package': 1},
 {'id': 18937,
  'teacher_id': 815733,
  'language': 'korean',
  'title': 'General Korean Class – From A to Z, For Everyone',
  'session_price': 3200,
  'student_count': 322,
  'session_count': 2045,
  'has_package': 1},
 {'id': 19298,
  'teacher_id': 436016,
  'language': 'chinese',
  'title': 'Informal Tutoring',
  'session_price': 1300,
  'student_count': 45,
  'session_count': 205,
  'has_package': 1},
 {'id': 19319,
  'teacher_id': 818089,
  'language': 'hindi',
  'title': 'Hindi Advanced Proficiency Courses- B 1, B2 , C 1 & C 2',
  'session_price': 2600,
  'student_count': 37,
  'session_count': 414,
  'has_package': 1},
 {'id': 19564,
  'teacher_id': 502096,
  'language': 'italian',
  'title': 'Informal Tutoring',
  'session_price': 2300,
  'student_count': 14,
  'session_count': 27,
  'has_package': 1},
 {'id': 19668,
  'teacher_id': 707465,
  'language': 'english',
  'title': 'Informal Tutoring',
  'session_price': 3000,
  'student_count': 75,
  'session_count': 389,
  'has_package': 1},
 {'id': 20093,
  'teacher_id': 889879,
  'language': 'spanish',
  'title': 'General Spanish lesson',
  'session_price': 2000,
  'student_count': 168,
  'session_count': 2349,
  'has_package': 1},
 {'id': 20328,
  'teacher_id': 517538,
  'language': 'spanish',
  'title': 'Comunicarse en español - Sesiones de conversación',
  'session_price': 2000,
  'student_count': 134,
  'session_count': 591,
  'has_package': 1},
 {'id': 20444,
  'teacher_id': 740680,
  'language': 'french',
  'title': 'Informal Tutoring',
  'session_price': 2000,
  'student_count': 435,
  'session_count': 5178,
  'has_package': 1},
 {'id': 20710,
  'teacher_id': 291538,
  'language': 'japanese',
  'title': 'Informal Tutoring (free conversation) | 会話練習',
  'session_price': 2480,
  'student_count': 152,
  'session_count': 563,
  'has_package': 1},
 {'id': 20714,
  'teacher_id': 516278,
  'language': 'german',
  'title': 'Konversation',
  'session_price': 2490,
  'student_count': 211,
  'session_count': 1368,
  'has_package': 1},
 {'id': 20813,
  'teacher_id': 953599,
  'language': 'english',
  'title': 'Conversation/Freetalking/Article discussion/Debate',
  'session_price': 1900,
  'student_count': 172,
  'session_count': 1080,
  'has_package': 1},
 {'id': 20964,
  'teacher_id': 591602,
  'language': 'japanese',
  'title': '⭐上級日本語会話\u300030 minutes\u3000(JLPT N2以上の合格者のみ。日本時間で月曜日～木曜日の13:00-16:30のみ。)',
  'session_price': 2000,
  'student_count': 140,
  'session_count': 1394,
  'has_package': 0},
 {'id': 21085,
  'teacher_id': 835769,
  'language': 'chinese',
  'title': 'Informal Tutoring',
  'session_price': 3000,
  'student_count': 97,
  'session_count': 1049,
  'has_package': 1},
 {'id': 21230,
  'teacher_id': 530071,
  'language': 'french',
  'title': 'Practice and answers to your questions // Pratique et réponse rapide aux questions',
  'session_price': 3000,
  'student_count': 12,
  'session_count': 61,
  'has_package': 1},
 {'id': 21269,
  'teacher_id': 596847,
  'language': 'english',
  'title': 'Improve your fluency',
  'session_price': 2500,
  'student_count': 94,
  'session_count': 1335,

In [174]:
with open('./pro_course_cleaned.json', 'w') as file:
        json.dump(pro_course_cleaned, file, indent=4)

Check if there are duplicated price list items\
Check if every price list item is linked to a course

In [57]:
with open('../data_extraction/price_list.json', 'r') as file:
    price_list = json.load(file)

df_price_list = pd.DataFrame(price_list)

In [58]:
with open('./pro_course_cleaned.json', 'r') as file:
    pro_course_cleaned = json.load(file)

df_pro_course_cleaned = pd.DataFrame(pro_course_cleaned)

In [59]:
df_price_list

,package_price,session_price,course_id,package_length,session_length,course_price_id
0,15200,3200,146280,5,2,353199
1,22000,4600,146280,5,3,353200
2,30000,6000,146280,5,4,353198
3,59000,6000,146280,10,4,1017005
4,14300,3000,146282,5,2,353214
...,...,...,...,...,...,...
216257,25000,5000,139499,5,4,333866
216258,67500,5000,139499,15,4,790345
216259,7000,7000,139502,1,4,333870
216260,25000,5000,139510,5,4,745677
216261,67500,5000,139510,15,4,790347

There are duplicated price list items

In [60]:
df_price_list['course_price_id'].nunique()

215827

There are 435 duplicated course_price_ids and there are no course_price_ids that occur 3 times or more.\
From the sample check, the duplicates arise because of the teacher updating the prices or package/session length

In [61]:
df_price_list_dup = df_price_list.groupby('course_price_id').count()
df_price_list_dup.reset_index()
df_price_list_dup[df_price_list_dup['package_price'] > 1]

,package_price,session_price,course_id,package_length,session_length
course_price_id,,,,,
137868,2,2,2,2,2
137869,2,2,2,2,2
145354,2,2,2,2,2
151723,2,2,2,2,2
151727,2,2,2,2,2
...,...,...,...,...,...
1082724,2,2,2,2,2
1082725,2,2,2,2,2
1082726,2,2,2,2,2
1082907,2,2,2,2,2
1083636,2,2,2,2,2

In [62]:
all_duplicates = df_price_list[df_price_list.duplicated(subset=['course_price_id'], keep=False)]
all_duplicates

,package_price,session_price,course_id,package_length,session_length,course_price_id
5951,2600,600,288693,5,3,1065695
5952,5500,600,288693,10,3,1072763
5954,3000,700,288693,5,4,1065693
5956,10000,700,288693,15,4,1072764
5958,4000,900,290681,5,4,1083636
...,...,...,...,...,...,...
201593,7000,1400,274689,5,4,1075021
201594,14000,1400,274689,10,4,1075022
206621,23999,4999,107142,5,4,237738
206622,47999,4999,107142,10,4,793758
206623,69999,4999,107142,15,4,793759

In [63]:
all_duplicates[all_duplicates['course_price_id'] == 1083636]

,package_price,session_price,course_id,package_length,session_length,course_price_id
5958,4000,900,290681,5,4,1083636
104896,4300,900,290681,5,4,1083636

In [64]:
df_price_list_sorted = df_price_list.sort_values(by=['course_price_id', 'package_price', 'session_price'], ascending=[True, True, True])
df_price_list_no_dup = df_price_list_sorted.drop_duplicates(subset=['course_price_id', 'course_id'], keep='last')
df_price_list_no_dup

,package_price,session_price,course_id,package_length,session_length,course_price_id
127459,1100,1100,375,1,3,336
127461,10000,1000,555,10,2,494
67410,20900,2300,946,10,4,823
127467,12000,1300,3190,10,3,3075
127465,10000,1000,3190,10,2,3076
...,...,...,...,...,...,...
140883,10200,1100,287665,10,3,1084998
140884,15000,1100,287665,15,3,1084999
140885,20000,1100,287665,20,3,1085000
204373,59999,7498,87801,10,4,1085029
204374,84999,7498,87801,15,4,1085030

In [65]:
df_pro_course_cleaned

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
0,375,436016,english,English courses新概念英语（1）,1400,15,106,0
1,555,436016,chinese,Young Learners' Chinese,1600,5,37,1
2,946,502096,serbian,Serbian for all levels! 100% target language l...,2300,80,1113,1
3,3190,436016,chinese,One-on-One Customized Chinese lesson,1500,73,1391,1
4,4042,463477,english,One-on-One tutoring: English,3200,95,1504,1
...,...,...,...,...,...,...,...,...
39030,290784,31481128,french,🗣️ Natural French Conversation: Speak easily !,700,0,0,1
39031,290785,8513543,french,Leçon d'essai,800,0,0,0
39032,290788,29325526,korean,For Long-term Students,1300,0,0,1
39033,290792,6417813,spanish,DELE exam preparation / Preparación para el ex...,2700,0,0,1
39034,290796,31472940,french,French for Kids and Beginners,4000,0,0,1

When the pro course dataframe is joined with the cleaned price list data frame, both left-anti and right-anti join do not return any rows.\
This means that there are no ids that are not mapped between the two tables.\
All the prices are linked to a course.

In [66]:
df_merged = pd.merge(df_pro_course_cleaned, df_price_list_no_dup, left_on='id', right_on='course_id', how='right_anti')
# df_merged = pd.merge(df_pro_course_cleaned, df_price_list_no_dup, left_on='id', right_on='course_id', how='left_anti')
df_merged

Empty DataFrame
Columns: [id, teacher_id, language, title, session_price_x, student_count, session_count, has_package, package_price, session_price_y, course_id, package_length, session_length, course_price_id]
Index: []

In [68]:
price_list_cleaned = df_price_list_no_dup.to_dict(orient='records')

In [69]:
price_list_cleaned

[{'package_price': 1100,
  'session_price': 1100,
  'course_id': 375,
  'package_length': 1,
  'session_length': 3,
  'course_price_id': 336},
 {'package_price': 10000,
  'session_price': 1000,
  'course_id': 555,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 494},
 {'package_price': 20900,
  'session_price': 2300,
  'course_id': 946,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 823},
 {'package_price': 12000,
  'session_price': 1300,
  'course_id': 3190,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 3075},
 {'package_price': 10000,
  'session_price': 1000,
  'course_id': 3190,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 3076},
 {'package_price': 30500,
  'session_price': 3200,
  'course_id': 4042,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 3934},
 {'package_price': 24300,
  'session_price': 2700,
  'course_id': 5620,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 5524},
 {'package_price': 30900,
  'session_price': 3400,
  'course_id': 5620,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 5525},
 {'package_price': 20900,
  'session_price': 2300,
  'course_id': 5779,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 5686},
 {'package_price': 16000,
  'session_price': 1800,
  'course_id': 6470,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 6375},
 {'package_price': 9000,
  'session_price': 1800,
  'course_id': 7313,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 7224},
 {'package_price': 11000,
  'session_price': 1200,
  'course_id': 8775,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 8795},
 {'package_price': 13000,
  'session_price': 1390,
  'course_id': 8775,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 8796},
 {'package_price': 15000,
  'session_price': 1590,
  'course_id': 8775,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 8797},
 {'package_price': 25000,
  'session_price': 2590,
  'course_id': 8775,
  'package_length': 10,
  'session_length': 6,
  'course_price_id': 8798},
 {'package_price': 189900,
  'session_price': 6090,
  'course_id': 9022,
  'package_length': 50,
  'session_length': 4,
  'course_price_id': 9117},
 {'package_price': 172900,
  'session_price': 6090,
  'course_id': 9024,
  'package_length': 40,
  'session_length': 4,
  'course_price_id': 9119},
 {'package_price': 5600,
  'session_price': 1300,
  'course_id': 9835,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 10181},
 {'package_price': 7000,
  'session_price': 1600,
  'course_id': 9835,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 10182},
 {'package_price': 10000,
  'session_price': 1000,
  'course_id': 9878,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 10230},
 {'package_price': 13000,
  'session_price': 1300,
  'course_id': 9878,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 10231},
 {'package_price': 10000,
  'session_price': 1000,
  'course_id': 9879,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 10234},
 {'package_price': 12000,
  'session_price': 1200,
  'course_id': 9879,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 10235},
 {'package_price': 12000,
  'session_price': 1200,
  'course_id': 10083,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 10471},
 {'package_price': 5000,
  'session_price': 1000,
  'course_id': 10083,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 10472},
 {'package_price': 11000,
  'session_price': 1200,
  'course_id': 10102,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 10492},
 {'package_price': 16000,
  'session_price': 1700,
  'course_id': 10102,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 10494},
 {'package_price': 139900,
  'session_price': 6090,
  'course_id': 10161,
  'package_length': 30,
  'session_length': 4,
  'course_price_id': 10573},
 {'package_price': 183900,
  'session_price': 7990,
  'course_id': 10161,
  'package_length': 30,
  'session_length': 6,
  'course_price_id': 10574},
 {'package_price': 7500,
  'session_price': 7500,
  'course_id': 10780,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 11382},
 {'package_price': 16200,
  'session_price': 1800,
  'course_id': 10796,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 11403},
 {'package_price': 15000,
  'session_price': 1590,
  'course_id': 11184,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 11916},
 {'package_price': 1800,
  'session_price': 1800,
  'course_id': 11263,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 12018},
 {'package_price': 1000,
  'session_price': 1000,
  'course_id': 11263,
  'package_length': 1,
  'session_length': 2,
  'course_price_id': 12019},
 {'package_price': 22500,
  'session_price': 2500,
  'course_id': 11444,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 12270},
 {'package_price': 20160,
  'session_price': 2100,
  'course_id': 11746,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 12692},
 {'package_price': 25920,
  'session_price': 2880,
  'course_id': 12030,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 13048},
 {'package_price': 4900,
  'session_price': 4900,
  'course_id': 12032,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 13049},
 {'package_price': 22000,
  'session_price': 5200,
  'course_id': 13127,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 14426},
 {'package_price': 27000,
  'session_price': 2800,
  'course_id': 13175,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 14480},
 {'package_price': 12000,
  'session_price': 2600,
  'course_id': 13193,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 14497},
 {'package_price': 5000,
  'session_price': 1000,
  'course_id': 13267,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 14578},
 {'package_price': 20900,
  'session_price': 2300,
  'course_id': 13335,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 14669},
 {'package_price': 20500,
  'session_price': 4500,
  'course_id': 13362,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 14712},
 {'package_price': 5000,
  'session_price': 1000,
  'course_id': 13600,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 14994},
 {'package_price': 27000,
  'session_price': 2900,
  'course_id': 14210,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 15764},
 {'package_price': 27000,
  'session_price': 2800,
  'course_id': 14653,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 16364},
 {'package_price': 8800,
  'session_price': 1800,
  'course_id': 14683,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 16405},
 {'package_price': 11500,
  'session_price': 2400,
  'course_id': 14683,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 16406},
 {'package_price': 14000,
  'session_price': 3000,
  'course_id': 14683,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 16407},
 {'package_price': 15000,
  'session_price': 3200,
  'course_id': 14706,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 16435},
 {'package_price': 17000,
  'session_price': 1800,
  'course_id': 14741,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 16491},
 {'package_price': 17000,
  'session_price': 1800,
  'course_id': 14844,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 16637},
 {'package_price': 17000,
  'session_price': 1800,
  'course_id': 14845,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 16638},
 {'package_price': 10000,
  'session_price': 2000,
  'course_id': 15639,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 17630},
 {'package_price': 6000,
  'session_price': 1200,
  'course_id': 15640,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 17631},
 {'package_price': 10000,
  'session_price': 2000,
  'course_id': 15641,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 17632},
 {'package_price': 9000,
  'session_price': 1800,
  'course_id': 15702,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 17711},
 {'package_price': 13000,
  'session_price': 1400,
  'course_id': 15797,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 17821},
 {'package_price': 9000,
  'session_price': 2000,
  'course_id': 17115,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 19561},
 {'package_price': 28500,
  'session_price': 5800,
  'course_id': 17216,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 19692},
 {'package_price': 30000,
  'session_price': 3300,
  'course_id': 17390,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 19903},
 {'package_price': 17000,
  'session_price': 1800,
  'course_id': 17676,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 20300},
 {'package_price': 5000,
  'session_price': 1000,
  'course_id': 17826,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 20479},
 {'package_price': 12000,
  'session_price': 1300,
  'course_id': 18179,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 20912},
 {'package_price': 14000,
  'session_price': 1500,
  'course_id': 18179,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 20913},
 {'package_price': 15000,
  'session_price': 1600,
  'course_id': 18179,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 20914},
 {'package_price': 6400,
  'session_price': 1300,
  'course_id': 18298,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 21074},
 {'package_price': 9800,
  'session_price': 2000,
  'course_id': 18298,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 21076},
 {'package_price': 10000,
  'session_price': 1100,
  'course_id': 18316,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 21094},
 {'package_price': 12000,
  'session_price': 1300,
  'course_id': 18316,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 21095},
 {'package_price': 13000,
  'session_price': 1400,
  'course_id': 18316,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 21096},
 {'package_price': 10000,
  'session_price': 1100,
  'course_id': 18328,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 21104},
 {'package_price': 12000,
  'session_price': 1300,
  'course_id': 18328,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 21105},
 {'package_price': 13500,
  'session_price': 1500,
  'course_id': 18506,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 21292},
 {'package_price': 9500,
  'session_price': 2000,
  'course_id': 18937,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 21742},
 {'package_price': 12500,
  'session_price': 2600,
  'course_id': 18937,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 21743},
 {'package_price': 15000,
  'session_price': 3200,
  'course_id': 18937,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 21744},
 {'package_price': 10000,
  'session_price': 1000,
  'course_id': 19298,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 22105},
 {'package_price': 17000,
  'session_price': 1800,
  'course_id': 19319,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 22125},
 {'package_price': 20900,
  'session_price': 2300,
  'course_id': 19564,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 22368},
 {'package_price': 7000,
  'session_price': 1500,
  'course_id': 19668,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 22472},
 {'package_price': 18000,
  'session_price': 2000,
  'course_id': 20328,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 23147},
 {'package_price': 1480,
  'session_price': 1480,
  'course_id': 20710,
  'package_length': 1,
  'session_length': 2,
  'course_price_id': 23530},
 {'package_price': 8300,
  'session_price': 1689,
  'course_id': 20714,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 23534},
 {'package_price': 6100,
  'session_price': 1250,
  'course_id': 20813,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 23642},
 {'package_price': 9400,
  'session_price': 1900,
  'course_id': 20813,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 23643},
 {'package_price': 1500,
  'session_price': 1500,
  'course_id': 20964,
  'package_length': 1,
  'session_length': 2,
  'course_price_id': 23798},
 {'package_price': 18600,
  'session_price': 2000,
  'course_id': 21085,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 23920},
 {'package_price': 28600,
  'session_price': 3000,
  'course_id': 21230,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 24065},
 {'package_price': 21340,
  'session_price': 2200,
  'course_id': 21384,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 24223},
 {'package_price': 8800,
  'session_price': 2000,
  'course_id': 21387,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 24228},
 {'package_price': 7500,
  'session_price': 1500,
  'course_id': 21396,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 24242},
 {'package_price': 3000,
  'session_price': 600,
  'course_id': 21669,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 24522},
 {'package_price': 1800,
  'session_price': 1800,
  'course_id': 21716,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 24567},
 {'package_price': 11500,
  'session_price': 1200,
  'course_id': 21784,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 24631},
 {'package_price': 5500,
  'session_price': 1200,
  'course_id': 21806,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 24659},
 {'package_price': 46000,
  'session_price': 2500,
  'course_id': 21928,
  'package_length': 20,
  'session_length': 2,
  'course_price_id': 24801},
 {'package_price': 56000,
  'session_price': 3000,
  'course_id': 21928,
  'package_length': 20,
  'session_length': 3,
  'course_price_id': 24802},
 {'package_price': 66000,
  'session_price': 3500,
  'course_id': 21928,
  'package_length': 20,
  'session_length': 4,
  'course_price_id': 24803},
 {'package_price': 46000,
  'session_price': 2500,
  'course_id': 21929,
  'package_length': 20,
  'session_length': 2,
  'course_price_id': 24805},
 {'package_price': 56000,
  'session_price': 3000,
  'course_id': 21929,
  'package_length': 20,
  'session_length': 3,
  'course_price_id': 24806},
 {'package_price': 66000,
  'session_price': 3500,
  'course_id': 21929,
  'package_length': 20,
  'session_length': 4,
  'course_price_id': 24807},
 {'package_price': 1000,
  'session_price': 1000,
  'course_id': 21991,
  'package_length': 1,
  'session_length': 2,
  'course_price_id': 24891},
 {'package_price': 10350,
  'session_price': 2150,
  'course_id': 22074,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 24972},
 {'package_price': 2400,
  'session_price': 2400,
  'course_id': 22397,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 25356},
 {'package_price': 46000,
  'session_price': 2500,
  'course_id': 22404,
  'package_length': 20,
  'session_length': 2,
  'course_price_id': 25363},
 {'package_price': 13000,
  'session_price': 1390,
  'course_id': 22918,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 26032},
 {'package_price': 13000,
  'session_price': 1390,
  'course_id': 22919,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 26033},
 {'package_price': 15000,
  'session_price': 1590,
  'course_id': 22919,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 26034},
 {'package_price': 11000,
  'session_price': 1200,
  'course_id': 22919,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 26035},
 {'package_price': 25000,
  'session_price': 2580,
  'course_id': 22919,
  'package_length': 10,
  'session_length': 6,
  'course_price_id': 26036},
 {'package_price': 1800,
  'session_price': 1800,
  'course_id': 22929,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 26050},
 {'package_price': 40000,
  'session_price': 4200,
  'course_id': 23424,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 26685},
 {'package_price': 2000,
  'session_price': 2000,
  'course_id': 23479,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 26747},
 {'package_price': 2000,
  'session_price': 2000,
  'course_id': 23480,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 26748},
 {'package_price': 2999,
  'session_price': 2999,
  'course_id': 23573,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 26858},
 {'package_price': 14500,
  'session_price': 2999,
  'course_id': 23574,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 26860},
 {'package_price': 9500,
  'session_price': 1998,
  'course_id': 23574,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 26861},
 {'package_price': 12500,
  'session_price': 2599,
  'course_id': 23575,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 26862},
 {'package_price': 14500,
  'session_price': 2999,
  'course_id': 23575,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 26863},
 {'package_price': 6500,
  'session_price': 1400,
  'course_id': 23841,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 27177},
 {'package_price': 9500,
  'session_price': 2100,
  'course_id': 23923,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 27275},
 {'package_price': 22500,
  'session_price': 2500,
  'course_id': 23978,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 27341},
 {'package_price': 24400,
  'session_price': 5000,
  'course_id': 24214,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 27659},
 {'package_price': 5000,
  'session_price': 2000,
  'course_id': 24223,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 27671},
 {'package_price': 15000,
  'session_price': 1600,
  'course_id': 24244,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 27700},
 {'package_price': 17000,
  'session_price': 1800,
  'course_id': 24247,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 27703},
 {'package_price': 15000,
  'session_price': 1600,
  'course_id': 24251,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 27708},
 {'package_price': 17000,
  'session_price': 1800,
  'course_id': 24252,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 27709},
 {'package_price': 1200,
  'session_price': 1200,
  'course_id': 24260,
  'package_length': 1,
  'session_length': 3,
  'course_price_id': 27723},
 {'package_price': 5500,
  'session_price': 1200,
  'course_id': 24285,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 27760},
 {'package_price': 17000,
  'session_price': 1800,
  'course_id': 24412,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 27929},
 {'package_price': 9500,
  'session_price': 2000,
  'course_id': 20444,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 27980},
 {'package_price': 6000,
  'session_price': 1300,
  'course_id': 24285,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 28098},
 {'package_price': 19000,

In [70]:
with open('./price_list_cleaned.json', 'w') as file:
        json.dump(price_list_cleaned, file, indent=4)